"""Report Generator - Produces professional plagiarism reports for admin review.

 Generates:
 1. Summary Report (PDF/HTML)
 2. Side-by-side code comparison
 3. Feature similarity breakdown
 4. Teacher recommendation section
"""
from typing import Dict, List, Any, Optional
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime

@dataclass
class ReportConfig:
    title: str = "CodeProvenance - Plagiarism Detection Report"
    institution: str = ""
    course: str = ""
    assignment: str = ""
    threshold: float = 0.5
    output_dir: Path = Path("./reports")
    format: str = "html"  # html, pdf

@dataclass
class ComparisonDetail:
    file_a: str
    file_b: str
    score: float
    risk: str
    features: Dict[str, float] = field(default_factory=dict)
    code_a: str = ""
    code_b: str = ""
    matched_regions: List[Dict[str, Any]] = field(default_factory=list)

class ReportGenerator:
    """Generates professional plagiarism reports."""
    
    def __init__(self, config: ReportConfig = None):
        self.config = config or ReportConfig()
        self.config.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_html(self, comparisons: List[ComparisonDetail], 
                      report_path: Path = None) -> Path:
        """Generate comprehensive HTML report."""
        path = report_path or self.config.output_dir / "plagiarism_report.html"
        
        html = f"""<!DOCTYPE html>
<html><head>
    <title>{self.config.title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }}
        .meta {{ color: #666; margin-bottom: 30px; }}
        .summary {{ background: #f5f5f5; padding: 20px; border-radius: 5px; margin-bottom: 30px; }}
        .risk-critical {{ color: #dc3545; font-weight: bold; }}
        .risk-high {{ color: #fd7e14; font-weight: bold; }}
        .risk-medium {{ color: #ffc107; }}
        .risk-low {{ color: #28a745; }}
        .comparison {{ border: 1px solid #ddd; padding: 20px; margin: 20px 0; border-radius: 5px; }}
        .header {{ display: flex; justify-content: space-between; align-items: center; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #f5f5f5; }}
        .features {{ margin: 10px 0; }}
        .features span {{ background: #e9ecef; padding: 2px 8px; margin: 2px; border-radius: 3px; }}
        pre {{ background: #f8f9fa; padding: 10px; overflow-x: auto; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }}
    </style>
</head><body>
    <h1>{self.config.title}</h1>
    <div class="meta">
        Institution: {self.config.institution or 'N/A'}<br>
        Course: {self.config.course or 'N/A'}<br>
        Assignment: {self.config.assignment or 'N/A'}<br>
        Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br>
        Threshold: {self.config.threshold}
    </div>"""
        
        # Summary
        total = len(comparisons)
        suspicious = [c for c in comparisons if c.score >= self.config.threshold]
        high_risk = [c for c in comparisons if c.risk in ('CRITICAL', 'HIGH')]
        
        html += f"""
    <div class="summary">
        <h2>Summary</h2>
        Total pairs analyzed: {total}<br>
        Suspicious pairs (≥{self.config.threshold}): {len(suspicious)}<br>
        High risk pairs: {len(high_risk)}
    </div>"""
        
        # Detailed comparisons
        html += "\n    <h2>Detailed Comparisons</h2>"
        for cmp in comparisons:
            risk_class = f"risk-{cmp.risk.lower()}"
            html += f"""
    <div class="comparison">
        <div class="header">
            <h3>{cmp.file_a} ↔ {cmp.file_b}</h3>
            <span class="{risk_class}">{cmp.risk} ({cmp.score:.3f})</span>
        </div>
        <div class="features">Features:
            {"".join(f'<span>{k}: {v:.3f}</span>' for k, v in cmp.features.items())}
        </div>
        <details>
            <summary>View Code Comparison</summary>
            <table><tr><th>File A</th><th>File B</th></tr>
            <tr><td><pre>{cmp.code_a[:500]}</pre></td>
            <td><pre>{cmp.code_b[:500]}</pre></td></tr>
            </table>
        </details>
    </div>"""
        
        # Footer
        html += """
    <div class="footer">
        <p>Generated by CodeProvenance Plagiarism Detection System</p>
    </div>
</body></html>"""
        
        path.write_text(html, encoding='utf-8')
        return path
    
    def generate_json(self, comparisons: List[ComparisonDetail],
                     path: Path = None) -> Path:
        """Generate JSON report."""
        path = path or self.config.output_dir / "plagiarism_report.json"
        import json
        data = {
            'title': self.config.title,
            'institution': self.config.institution,
            'course': self.config.course,
            'assignment': self.config.assignment,
            'threshold': self.config.threshold,
            'generated': datetime.now().isoformat(),
            'comparisons': [
                {'file_a': c.file_a, 'file_b': c.file_b, 'score': round(c.score, 3),
                 'risk': c.risk, 'features': {k: round(v, 3) for k, v in c.features.items()}}
                for c in comparisons
            ]
        }
        path.write_text(json.dumps(data, indent=2))
        return path
