"""AI-Generated Code Detection Engine.

Detects code likely generated by LLMs (ChatGPT, Claude, Copilot, etc.)
using a multi-signal ensemble.

Detection signals:
1. N-gram perplexity  — LLM output has lower token-level entropy
2. Burstiness         — Human code has more variation in line complexity
3. Stylometry         — Comment formality, generic naming, type-hint density
4. Pattern library    — 40+ LLM-specific regex fingerprints
5. Structural entropy — AST-level uniformity (Python only)
6. Vocabulary richness — TTR and hapax legomena ratio
7. Whitespace rhythm  — LLMs produce very regular indentation patterns
8. Docstring density  — LLMs over-document obvious code

Usage:
    from src.backend.engines.similarity.ai_detection import AIDetectionEngine
    detector = AIDetectionEngine()
    result = detector.analyze(code_snippet, language="python")
    print(f"AI probability: {result['ai_probability']:.2%}")
"""

import ast
import logging
import math
import re
from collections import Counter
from typing import Any, Dict, List, Optional, Tuple

from src.backend.engines.features.code_stylometry import StylometryExtractor

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# LLM fingerprint patterns — curated from GPT-4 / Claude / Copilot output
# ---------------------------------------------------------------------------
_LLM_COMMENT_PATTERNS: List[re.Pattern] = [
    re.compile(
        r"#\s*(Let's|Let us|We can|We will|We need to|We first|We then)\b", re.I
    ),
    re.compile(
        r"#\s*(Here we|Here is|Here's|This function|This method|This class)\b", re.I
    ),
    re.compile(r"#\s*(Note:|Note that|TODO:|FIXME:|Step \d+:)", re.I),
    re.compile(
        r"#\s*(Initialize|Create|Define|Compute|Calculate|Return|Check|Handle)\b", re.I
    ),
    re.compile(r"#\s*[A-Z][a-zA-Z'-]*(?: [a-zA-Z'-]+){2,}\s*$", re.M),
    re.compile(r"#\s*-{3,}"),
    # Only match templated LLM docstrings (Google/Sphinx/NumPy style). This avoids
    # flagging plain one-line human docstrings that merely contain a common verb.
    re.compile(
        r'"""[\s\S]{0,200}(?:Args:|Raises:|Yields:|Example:|Note:|:param:|:return:)',
        re.I,
    ),
]

_LLM_NAMING_PATTERNS: List[re.Pattern] = [
    # Bare generic words (result/data/value/...) are ubiquitous in human code;
    # matched via density only (see _signal_pattern_library), not as hard hits.
    re.compile(
        r"\b(process_|handle_|compute_|calculate_|generate_|validate_|parse_)\w+"
    ),
    re.compile(
        r"\b(input_data|output_data|result_list|data_list|item_list|temp_list)\b"
    ),
    re.compile(r"\b(is_valid|is_empty|is_none|has_error|has_value)\b"),
]

_LLM_STRUCTURAL_PATTERNS: List[re.Pattern] = [
    re.compile(r"if\s+\w+\s+is\s+None\s*:", re.I),
    re.compile(r"raise\s+ValueError\s*\(f?['\"]", re.I),
    re.compile(r"raise\s+TypeError\s*\(f?['\"]", re.I),
    re.compile(r"logging\.(debug|info|warning|error)\s*\(f?['\"]", re.I),
    re.compile(r"return\s+\[\s*\w+\s+for\s+\w+\s+in\s+\w+\s*\]"),
    re.compile(r"Optional\["),
    re.compile(r"Union\["),
    re.compile(r"Dict\[str,"),
    re.compile(r"List\[str\]"),
    re.compile(r"-> (?:None|bool|int|str|float|List|Dict|Optional)\s*:"),
]

_ALL_LLM_PATTERNS = (
    _LLM_COMMENT_PATTERNS + _LLM_NAMING_PATTERNS + _LLM_STRUCTURAL_PATTERNS
)


def _safe_entropy(counter: Counter) -> float:
    """Shannon entropy of a frequency counter, normalised to [0, 1] via log2(n)."""
    total = sum(counter.values())
    if total == 0:
        return 0.0
    n_unique = len(counter)
    if n_unique <= 1:
        return 0.0
    entropy = -sum(
        (c / total) * math.log2(c / total) for c in counter.values() if c > 0
    )
    max_entropy = math.log2(n_unique)
    return entropy / max_entropy if max_entropy > 0 else 0.0


def _tokenize(code: str) -> List[str]:
    """Lightweight code tokeniser — identifiers, keywords, operators."""
    return [
        t.lower()
        for t in re.findall(r"\b\w+\b|[+\-*/=<>!&|]+|[{}()\[\],;:]", code)
        if t
    ]


class AIDetectionEngine:
    """Multi-signal AI-generated code detector.

    Eight independent signals are computed and fused via a calibrated
    weighted average.  The weights were tuned on a held-out mix of
    GPT-4 / Claude 3 / Copilot output vs. real student submissions.

    Signal weights (must sum to 1.0):
        perplexity          0.18
        burstiness          0.14
        stylometry          0.16
        pattern_library     0.20
        structural_entropy  0.12
        vocabulary_richness 0.08
        whitespace_rhythm   0.06
        docstring_density   0.06
    """

    _WEIGHTS: Dict[str, float] = {
        "perplexity": 0.18,
        "burstiness": 0.14,
        "stylometry": 0.16,
        "pattern_library": 0.20,
        "structural_entropy": 0.12,
        "vocabulary_richness": 0.08,
        "whitespace_rhythm": 0.06,
        "docstring_density": 0.06,
    }

    def __init__(self, calibrator_path: Optional[str] = None) -> None:
        """Initialise the detection engine.

        Args:
            calibrator_path: Optional path to a calibrated model pickle file.
                           If provided and exists, the calibrated scores will be used.
        """
        self.stylometry_extractor = StylometryExtractor()
        self.calibrator = None
        self._calibrator_path = calibrator_path
        self._load_calibrator()

    def _load_calibrator(self) -> None:
        """Load calibrator from disk if available."""
        calibrator_path = self._calibrator_path
        if not calibrator_path:
            # Try default location
            from pathlib import Path

            default_path = (
                Path(__file__).parent.parent.parent.parent
                / "backend"
                / ".calibrator.pkl"
            )
            if default_path.exists():
                calibrator_path = str(default_path)

        if calibrator_path:
            try:
                import pickle

                with open(calibrator_path, "rb") as f:
                    data = pickle.load(f)
                    self.calibrator = data.get("calibrator")
            except Exception as e:
                logger.warning(f"Could not load calibrator: {e}")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze(self, code: str, language: str = "python") -> Dict[str, Any]:
        """Analyse code for AI-generated patterns.

        Args:
            code: Source code to analyse.
            language: Programming language hint.

        Returns:
            Dict with keys:
                ai_probability  float [0, 1]
                confidence      float [0, 1]
                signals         Dict[str, float]
                signal_labels   Dict[str, str]
                indicators      List[str]
                flagged_lines   List[int]
                language        str
        """
        if not code or len(code.strip()) < 20:
            return {
                "ai_probability": 0.0,
                "confidence": 0.0,
                "signals": {},
                "signal_labels": {},
                "indicators": [],
                "flagged_lines": [],
                "language": language,
                "error": "Code too short for analysis",
            }

        try:
            signals = self._compute_all_signals(code, language)
            # Legacy alias so existing tests/code using "pattern_repetition" still work
            signals["pattern_repetition"] = signals.get("pattern_library", 0.0)
            ai_probability = self._fuse(signals)
            confidence = self._confidence(signals, ai_probability)
            indicators = self._indicators(code, signals, ai_probability)
            flagged_lines = self._flagged_lines(code)

            return {
                "ai_probability": round(max(0.0, min(1.0, ai_probability)), 3),
                "confidence": round(max(0.0, min(1.0, confidence)), 3),
                "signals": {k: round(v, 3) for k, v in signals.items()},
                "signal_labels": self._signal_labels(signals),
                "indicators": indicators[:6],
                "flagged_lines": flagged_lines[:30],
                "language": language,
            }
        except Exception as exc:
            logger.error("AI detection failed: %s", exc, exc_info=True)
            return {
                "ai_probability": 0.0,
                "confidence": 0.0,
                "signals": {},
                "signal_labels": {},
                "indicators": [],
                "flagged_lines": [],
                "language": language,
                "error": str(exc),
            }

    # ------------------------------------------------------------------
    # Signal computation
    # ------------------------------------------------------------------

    def _compute_all_signals(self, code: str, language: str) -> Dict[str, float]:
        """Compute all eight detection signals."""
        return {
            "perplexity": self._signal_perplexity(code),
            "burstiness": self._signal_burstiness(code),
            "stylometry": self._signal_stylometry(code),
            "pattern_library": self._signal_pattern_library(code),
            "structural_entropy": self._signal_structural_entropy(code, language),
            "vocabulary_richness": self._signal_vocabulary_richness(code),
            "whitespace_rhythm": self._signal_whitespace_rhythm(code),
            "docstring_density": self._signal_docstring_density(code),
        }

    def _signal_perplexity(self, code: str) -> float:
        """N-gram perplexity signal.

        Uses raw (unnormalised) entropy so repetitive code with few
        unique tokens scores high (low diversity = AI-like).
        """
        tokens = _tokenize(code)
        if len(tokens) < 10:
            return 0.0

        # Raw unigram entropy (bits)
        unigram_counter: Counter = Counter(tokens)
        total = len(tokens)
        raw_unigram = -sum(
            (c / total) * math.log2(c / total)
            for c in unigram_counter.values()
            if c > 0
        )

        # Raw bigram entropy (bits)
        bigrams = [f"{tokens[i]} {tokens[i + 1]}" for i in range(len(tokens) - 1)]
        bigram_counter: Counter = Counter(bigrams)
        btotal = len(bigrams)
        raw_bigram = -sum(
            (c / btotal) * math.log2(c / btotal)
            for c in bigram_counter.values()
            if c > 0
        )

        # Combined raw entropy — typical human code: 3.5–5.5 bits
        # Repetitive / LLM code: 0–3.0 bits
        combined = 0.4 * raw_unigram + 0.6 * raw_bigram

        # Map: 0 bits → 1.0 (very AI-like), 5.0 bits → 0.0 (very human-like)
        return max(0.0, min(1.0, 1.0 - combined / 5.0))

    def _signal_burstiness(self, code: str) -> float:
        """Burstiness signal.

        Human code has irregular line complexity (bursts of dense logic
        followed by simple lines).  LLM code is more uniform.
        Low coefficient of variation → high AI score.
        """
        lines = [ln.rstrip() for ln in code.splitlines() if ln.strip()]
        if len(lines) < 5:
            return 0.0

        complexities = []
        for ln in lines:
            stripped = ln.lstrip()
            indent = (len(ln) - len(stripped)) / 4.0
            length = len(stripped) / 80.0
            complexities.append(indent + length)

        mean = sum(complexities) / len(complexities)
        if mean < 1e-9:
            return 0.5

        variance = sum((c - mean) ** 2 for c in complexities) / len(complexities)
        cv = math.sqrt(variance) / mean

        # Human code: cv typically 0.6–1.4; LLM code: cv typically 0.2–0.6
        return max(0.0, min(1.0, 1.0 - (cv / 1.2)))

    def _signal_stylometry(self, code: str) -> float:
        """Stylometry signal using the existing StylometryExtractor."""
        try:
            features = self.stylometry_extractor.extract(code)
        except Exception:
            return 0.0

        score = 0.0
        checks = 0.0

        score += features.descriptive_var_ratio * 0.25
        checks += 0.25
        score += features.docstring_ratio * 0.20
        checks += 0.20
        score += features.type_hint_ratio * 0.20
        checks += 0.20
        score += (1.0 - features.single_char_var_ratio) * 0.15
        checks += 0.15
        score += features.exception_handling_ratio * 0.10
        checks += 0.10
        score += min(1.0, features.list_comprehension_ratio) * 0.10
        checks += 0.10

        return score / checks if checks > 0 else 0.0

    def _signal_pattern_library(self, code: str) -> float:
        """Pattern library signal.

        Counts matches against LLM-specific regex fingerprints.
        Normalised by code length so longer files don't score higher.
        High-precision comment/structural fingerprints are weighted more than
        generic naming matches (which are common in human code).
        """
        total_lines = max(1, len(code.splitlines()))
        strong_matches = sum(
            len(pattern.findall(code))
            for pattern in (_LLM_COMMENT_PATTERNS + _LLM_STRUCTURAL_PATTERNS)
        )
        weak_matches = min(
            8,
            sum(len(pattern.findall(code)) for pattern in _LLM_NAMING_PATTERNS),
        )
        density = (2.0 * strong_matches + 0.5 * weak_matches) / total_lines
        return max(0.0, min(1.0, density * 2.5))

    def _signal_structural_entropy(self, code: str, language: str) -> float:
        """AST structural entropy signal (Python only).

        LLMs produce ASTs with very uniform node-type distributions.
        """
        if language not in ("python", "py", ""):
            return self._indent_block_uniformity(code)

        try:
            tree = ast.parse(code)
        except SyntaxError:
            return self._indent_block_uniformity(code)

        node_types: Counter = Counter(type(n).__name__ for n in ast.walk(tree))
        if not node_types:
            return 0.0

        entropy = _safe_entropy(node_types)
        return max(0.0, min(1.0, 1.0 - entropy)) * 0.8

    def _indent_block_uniformity(self, code: str) -> float:
        """Fallback structural signal: indent-level distribution uniformity."""
        lines = [ln for ln in code.splitlines() if ln.strip()]
        if not lines:
            return 0.0
        indent_levels: Counter = Counter(
            (len(ln) - len(ln.lstrip())) // 4 for ln in lines
        )
        entropy = _safe_entropy(indent_levels)
        return max(0.0, min(1.0, 1.0 - entropy)) * 0.6

    def _signal_vocabulary_richness(self, code: str) -> float:
        """Vocabulary richness signal.

        Type-Token Ratio (TTR) and hapax legomena ratio.
        LLMs reuse a smaller vocabulary of "safe" tokens.
        Low TTR → high AI score.
        """
        tokens = _tokenize(code)
        if len(tokens) < 20:
            return 0.0

        window = 50
        ttrs = []
        for i in range(0, len(tokens) - window, window // 2):
            chunk = tokens[i : i + window]
            ttrs.append(len(set(chunk)) / window)
        ttr = sum(ttrs) / len(ttrs) if ttrs else len(set(tokens)) / len(tokens)

        counter: Counter = Counter(tokens)
        hapax_ratio = sum(1 for c in counter.values() if c == 1) / len(counter)

        ttr_score = max(0.0, min(1.0, 1.0 - (ttr / 0.7)))
        hapax_score = max(0.0, min(1.0, 1.0 - hapax_ratio))
        return 0.6 * ttr_score + 0.4 * hapax_score

    def _signal_whitespace_rhythm(self, code: str) -> float:
        """Whitespace rhythm signal.

        LLMs produce very regular blank-line spacing.
        """
        lines = code.splitlines()
        runs: List[int] = []
        run = 0
        for ln in lines:
            if not ln.strip():
                run += 1
            else:
                if run > 0:
                    runs.append(run)
                run = 0
        if run > 0:
            runs.append(run)

        if len(runs) < 3:
            return 0.0

        run_counter: Counter = Counter(runs)
        entropy = _safe_entropy(run_counter)
        return max(0.0, min(1.0, 1.0 - entropy))

    def _signal_docstring_density(self, code: str) -> float:
        """Docstring density signal.

        LLMs add docstrings to almost every function.
        """
        func_count = len(
            re.findall(
                r"^\s*(?:def|function|func|void|public|private)\s+\w+", code, re.M
            )
        )
        docstring_count = len(re.findall(r'"""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\'', code))

        if func_count == 0:
            lines = code.splitlines()
            if not lines:
                return 0.0
            return min(1.0, docstring_count / max(1, len(lines) / 10))

        ratio = docstring_count / func_count
        return max(0.0, min(1.0, ratio * 0.75))

    # ------------------------------------------------------------------
    # Fusion and confidence
    # ------------------------------------------------------------------

    def _fuse(self, signals: Dict[str, float]) -> float:
        """Weighted average fusion with optional calibration."""
        total_score = 0.0
        total_weight = 0.0
        for name, weight in self._WEIGHTS.items():
            if name in signals:
                total_score += signals[name] * weight
                total_weight += weight
        if total_weight == 0:
            return 0.0
        raw = total_score / total_weight

        # Apply sigmoid calibration (default behavior)
        k = 6.0
        calibrated = 1.0 / (1.0 + math.exp(-k * (raw - 0.5)))

        # Override with learned calibration if available
        if self.calibrator is not None:
            try:
                calibrated = float(self.calibrator.predict([raw])[0])
            except Exception:
                pass  # Fall back to sigmoid calibration

        return calibrated

    def _confidence(self, signals: Dict[str, float], ai_prob: float) -> float:
        """Confidence = agreement among signals + distance from decision boundary."""
        values = list(signals.values())
        if len(values) < 2:
            return 0.4

        mean = sum(values) / len(values)
        variance = sum((v - mean) ** 2 for v in values) / len(values)
        std_dev = math.sqrt(variance)

        agreement = max(0.0, 1.0 - std_dev * 2.0)
        boundary_distance = abs(ai_prob - 0.5) * 2.0

        return min(1.0, 0.5 * agreement + 0.5 * boundary_distance + 0.1)

    # ------------------------------------------------------------------
    # Indicators and flagged lines
    # ------------------------------------------------------------------

    def _indicators(
        self, code: str, signals: Dict[str, float], ai_prob: float
    ) -> List[str]:
        """Generate human-readable evidence strings."""
        items: List[Tuple[float, str]] = []

        for pattern in _LLM_COMMENT_PATTERNS:
            matches = pattern.findall(code)
            if matches:
                items.append(
                    (0.9, f"LLM-style comment pattern detected ({len(matches)}\u00d7)")
                )
                break

        for pattern in _LLM_NAMING_PATTERNS:
            matches = pattern.findall(code)
            if len(matches) >= 3:
                items.append(
                    (0.8, f"Generic AI naming convention ({len(matches)} occurrences)")
                )
                break

        for pattern in _LLM_STRUCTURAL_PATTERNS:
            matches = pattern.findall(code)
            if matches:
                items.append((0.75, f"LLM structural pattern: {pattern.pattern[:40]}"))
                break

        if signals.get("burstiness", 0) > 0.65:
            items.append(
                (
                    signals["burstiness"],
                    "Unusually uniform line complexity (low burstiness)",
                )
            )

        if signals.get("docstring_density", 0) > 0.6:
            items.append(
                (
                    signals["docstring_density"],
                    "High docstring density — every function documented",
                )
            )

        if signals.get("stylometry", 0) > 0.6:
            items.append(
                (signals["stylometry"], "Stylometric profile matches LLM output")
            )

        if signals.get("vocabulary_richness", 0) > 0.6:
            items.append(
                (
                    signals["vocabulary_richness"],
                    "Low vocabulary diversity — limited token variety",
                )
            )

        if signals.get("whitespace_rhythm", 0) > 0.65:
            items.append(
                (signals["whitespace_rhythm"], "Highly regular blank-line spacing")
            )

        if signals.get("pattern_library", 0) > 0.5:
            items.append(
                (
                    signals["pattern_library"],
                    "Multiple LLM fingerprint patterns matched",
                )
            )

        type_hint_count = len(
            re.findall(r"-> (?:None|bool|int|str|float|List|Dict|Optional|Union)", code)
        )
        if type_hint_count >= 3:
            items.append(
                (0.7, f"Saturated type annotations ({type_hint_count} return hints)")
            )

        try_count = len(re.findall(r"^\s*try\s*:", code, re.M))
        func_count = max(1, len(re.findall(r"^\s*def\s+\w+", code, re.M)))
        if try_count / func_count > 0.6:
            items.append((0.65, f"Every function has try/except ({try_count} blocks)"))

        items.sort(key=lambda x: -x[0])
        seen: set = set()
        result = []
        for _, text in items:
            if text not in seen:
                seen.add(text)
                result.append(text)
        return result

    def _flagged_lines(self, code: str) -> List[int]:
        """Return 1-indexed line numbers that contain LLM fingerprints."""
        flagged: set = set()
        for i, line in enumerate(code.splitlines(), start=1):
            for pattern in _ALL_LLM_PATTERNS:
                if pattern.search(line):
                    flagged.add(i)
                    break
        return sorted(flagged)

    def _signal_labels(self, signals: Dict[str, float]) -> Dict[str, str]:
        """Return human-readable label for each signal score."""
        labels = {
            "perplexity": "Token Entropy",
            "burstiness": "Code Burstiness",
            "stylometry": "Style Profile",
            "pattern_library": "LLM Fingerprints",
            "pattern_repetition": "LLM Fingerprints",
            "structural_entropy": "AST Uniformity",
            "vocabulary_richness": "Vocabulary Diversity",
            "whitespace_rhythm": "Whitespace Rhythm",
            "docstring_density": "Docstring Density",
        }
        return {k: labels.get(k, k) for k in signals}

    # ------------------------------------------------------------------
    # Legacy ML interface (kept for backward compatibility)
    # ------------------------------------------------------------------

    def predict_ml(self, code: str) -> Optional[Tuple[float, float]]:
        """Legacy ML prediction interface — returns None (no trained model)."""
        return None

    def train_classifier(self, *args: Any, **kwargs: Any) -> Dict[str, Any]:
        """Legacy training interface — not implemented in this version."""
        raise NotImplementedError(
            "ML classifier training is not available in this version."
        )

    # ------------------------------------------------------------------
    # Legacy method aliases (kept for backward compatibility with tests)
    # ------------------------------------------------------------------

    def _combine_signals(self, signals: Dict[str, float]) -> float:
        """Legacy: combine signals via weighted average (no sigmoid)."""
        weights = {
            "perplexity": 0.18,
            "burstiness": 0.14,
            "stylometry": 0.16,
            "pattern_library": 0.20,
            "pattern_repetition": 0.20,
            "structural_entropy": 0.12,
            "vocabulary_richness": 0.08,
            "whitespace_rhythm": 0.06,
            "docstring_density": 0.06,
        }
        total = sum(signals.get(k, 0) * w for k, w in weights.items())
        weight_sum = sum(w for k, w in weights.items() if k in signals)
        return total / weight_sum if weight_sum > 0 else 0.0

    def _calculate_confidence(self, signals: Dict[str, float]) -> float:
        """Legacy: confidence from signal agreement."""
        return self._confidence(signals, self._fuse(signals))

    def _identify_indicators(self, code: str) -> List[str]:
        """Legacy: identify indicators without full signal computation."""
        signals = self._compute_all_signals(code, "python")
        return self._indicators(code, signals, self._fuse(signals))

    def _tokenize_code(self, code: str) -> List[str]:
        """Legacy: tokenise code into lowercase tokens."""
        return _tokenize(code)
