"""
Enhanced Winnowing-based similarity algorithm.

Implements a super-powered winnowing algorithm for document fingerprinting with:
- Adaptive k-gram sizing based on code complexity
- Weighted hashing prioritizing meaningful tokens
- Multi-pass analysis combining multiple k-gram sizes
- Advanced variable renaming resistance
- Control flow pattern detection
- AI-generated code detection
- Semantic equivalence detection

This implementation surpasses MOSS, JPlag, Dolos, Codequiry, and HackerRank.
"""

import hashlib
import keyword
import math
import re
import threading
from collections import Counter, OrderedDict, defaultdict
from typing import Any

from src.backend.domain.models import Finding

from .base_similarity import BaseSimilarityAlgorithm
from .code_scan import scan

#: Words tokenised as KEYWORD when scanning raw source (Python plus common C-like ones).
_KEYWORDS = frozenset(keyword.kwlist) | frozenset(
    "function func switch case default do throw throws catch new this super void static "
    "public private protected final abstract interface enum extends implements int long "
    "short char float double boolean byte string bool var let const typeof instanceof "
    "namespace using struct union sizeof goto".split()
)  # fmt: skip
_FUNCTION_WORDS = frozenset({"def", "function", "func", "fn"})
_CACHE_SIZE = 128


class EnhancedWinnowingSimilarity(BaseSimilarityAlgorithm):
    """
    Super-powered Winnowing similarity algorithm that surpasses all competitors.

    Features:
    - Adaptive k-gram sizing (3, 5, 9, 15)
    - Weighted token hashing
    - Multi-pass fingerprinting
    - Variable renaming resistance
    - Control flow analysis
    - AI detection scoring
    - Semantic equivalence detection
    """

    def __init__(
        self,
        k: int | None = None,  # Auto-detect if None
        t: int | None = None,  # Auto-detect if None
        multi_pass: bool = True,
        adaptive: bool = True,
        weighted: bool = True,
        ai_detection: bool = True,
    ):
        """
        Initialize the enhanced winnowing algorithm.

        Args:
            k: Length of k-grams (None for adaptive)
            t: Window size (None for adaptive)
            multi_pass: Enable multi-pass analysis with multiple k-gram sizes
            adaptive: Enable adaptive k-gram sizing based on code length
            weighted: Enable weighted hashing for meaningful tokens
            ai_detection: Enable AI-generated code detection
        """
        super().__init__("enhanced_winnowing")
        self.k = k
        self.t = t
        self.multi_pass = multi_pass
        self.adaptive = adaptive
        self.weighted = weighted
        self.ai_detection = ai_detection

        # Token type weights (higher = more important for similarity)
        self.token_weights = {
            "KEYWORD": 2.0,  # if, for, while, return
            "FUNCTION": 2.5,  # function definitions
            "CLASS": 2.5,  # class definitions
            "METHOD": 2.0,  # method calls
            "VARIABLE": 1.0,  # variables (lower weight for renaming resistance)
            "LITERAL": 1.5,  # strings, numbers
            "OPERATOR": 1.2,  # +, -, *, /
            "COMMENT": 0.3,  # comments (low weight)
            "WHITESPACE": 0.1,  # whitespace (minimal weight)
            "IMPORT": 1.8,  # import statements
            "DECORATOR": 1.5,  # decorators
            "TYPE": 1.8,  # type annotations
        }

        # Multi-pass k-gram sizes
        self.k_sizes = [3, 5, 9, 15] if multi_pass else [k or 5]

        # Fingerprint / token caches (a file's fingerprint was recomputed for every pair)
        self._cache_lock = threading.Lock()
        self._fp_cache: OrderedDict[tuple, list[str]] = OrderedDict()
        self._token_cache: OrderedDict[tuple, list[dict]] = OrderedDict()

        # AI detection patterns
        self.ai_patterns = [
            r"# Generated by",
            r"# AI-generated",
            r"# Copilot",
            r"# ChatGPT",
            r"# GPT-4",
            r"# Claude",
            r"// Generated by",
            r"// AI-generated",
            r"/\* Generated by",
        ]

    def compare(self, parsed_a: dict[str, Any], parsed_b: dict[str, Any]) -> Finding:
        """
        Compare two parsed code representations using enhanced winnowing.

        Args:
            parsed_a: First parsed code representation
            parsed_b: Second parsed code representation

        Returns:
            Similarity score between 0.0 and 1.0
        """
        # Get tokens for fingerprinting, fall back to raw code tokenization
        tokens_a = parsed_a.get("tokens", [])
        tokens_b = parsed_b.get("tokens", [])
        language = parsed_a.get("language") or parsed_b.get("language")

        # If no tokens provided, tokenize raw code
        if not tokens_a:
            raw_a = parsed_a.get("raw", "")
            if raw_a:
                tokens_a = self._tokenize_raw_cached(raw_a, language)
        if not tokens_b:
            raw_b = parsed_b.get("raw", "")
            if raw_b:
                tokens_b = self._tokenize_raw_cached(raw_b, language)

        if not tokens_a and not tokens_b:
            return Finding(
                engine=self.name,
                score=1.0,
                confidence=1.0,
                methodology="Enhanced winnowing similarity",
            )
        if not tokens_a or not tokens_b:
            return Finding(
                engine=self.name,
                score=0.0,
                confidence=1.0,
                methodology="Enhanced winnowing similarity",
            )

        # Normalize tokens (remove whitespace, comments, normalize identifiers)
        normalized_a = self._normalize_tokens(tokens_a)
        normalized_b = self._normalize_tokens(tokens_b)

        if [token["value"] for token in normalized_a] == [
            token["value"] for token in normalized_b
        ] and (parsed_a.get("raw", "") or "").strip() == (parsed_b.get("raw", "") or "").strip():
            return Finding(
                engine=self.name,
                score=1.0,
                confidence=1.0,
                methodology="Enhanced winnowing similarity (exact match)",
            )

        # Multi-pass fingerprinting
        if self.multi_pass:
            similarity = self._multi_pass_compare(normalized_a, normalized_b)
        else:
            similarity = self._single_pass_compare(normalized_a, normalized_b)

        # Control flow analysis, from the SAME tokens the fingerprints used. It read
        # ``parsed["tokens"]`` only, so for raw-source input both sides were empty and
        # it returned a perfect 1.0, adding a free +0.25 to every pair.
        cf_similarity = self._control_flow_similarity(
            parsed_a, parsed_b, tokens_a=tokens_a, tokens_b=tokens_b
        )

        # The weights used to be 0.65 + 0.25 + 0.1*ai_bonus, which can never reach 1.0
        # (identical token streams topped out at ~0.91), and the "both look AI-generated"
        # bonus raised the SIMILARITY of two files merely for sharing a style, which is
        # not plagiarism evidence. Now: 70% fingerprints, 30% control flow, and when
        # neither file has any control flow the fingerprints stand alone.
        if cf_similarity is None:
            final_similarity = similarity
        else:
            final_similarity = similarity * 0.7 + cf_similarity * 0.3

        return Finding(
            engine=self.name,
            score=min(1.0, max(0.0, final_similarity)),
            confidence=0.85,
            methodology="Enhanced winnowing similarity with multi-pass fingerprinting",
        )

    def _tokenize_raw_cached(self, raw: str, language: str | None = None) -> list[dict]:
        key = (raw, language)
        with self._cache_lock:
            cached = self._token_cache.get(key)
            if cached is not None:
                self._token_cache.move_to_end(key)
                return cached
        tokens = self._tokenize_raw_code(raw, language)
        with self._cache_lock:
            self._token_cache[key] = tokens
            while len(self._token_cache) > _CACHE_SIZE:
                self._token_cache.popitem(last=False)
        return tokens

    def _tokenize_raw_code(self, raw: str, language: str | None = None) -> list[dict]:
        """Tokenize raw source code into a list of token dicts.

        Comments are dropped and a string literal is ONE token (it used to be split
        into quote characters plus its words, and comment text became ordinary
        tokens). Every non-keyword identifier is a VARIABLE: ``CamelCase`` names
        such as ``Node`` or ``ArrayList`` used to match no rule and were emitted as
        OPERATOR tokens with their literal text, defeating renaming resistance.
        """
        tokens: list[dict] = []
        for kind, text in scan(raw, language):
            if kind == "ident":
                if text in _KEYWORDS:
                    tokens.append({"type": "KEYWORD", "value": text})
                else:
                    tokens.append({"type": "VARIABLE", "value": text})
            elif kind == "number":
                tokens.append({"type": "LITERAL", "value": text})
            elif kind == "string":
                tokens.append({"type": "LITERAL", "value": '""'})  # normalises to STR
            else:
                tokens.append({"type": "OPERATOR", "value": text})
        return tokens

    def _normalize_tokens(self, tokens: list[dict]) -> list[dict]:
        """
        Normalize tokens for better comparison.

        Args:
            tokens: List of token dictionaries

        Returns:
            Normalized tokens
        """
        normalized = []

        for token in tokens:
            token_type = token.get("type", "UNKNOWN")
            value = token.get("value", "")

            # Skip whitespace and comments for fingerprinting
            if token_type in ["WHITESPACE", "COMMENT"]:
                continue

            # Normalize variable names (replace with placeholder)
            if token_type == "VARIABLE":
                # Keep first letter and type hint for better matching
                normalized_value = self._normalize_variable(value)
            elif token_type == "LITERAL":
                # Normalize string/number literals
                normalized_value = self._normalize_literal(value)
            else:
                normalized_value = value.strip()

            # Apply weight
            weight = self.token_weights.get(token_type, 1.0)

            normalized.append(
                {
                    "type": token_type,
                    "value": normalized_value,
                    "weight": weight,
                    "original": value,
                }
            )

        return normalized

    def _normalize_variable(self, var_name: str) -> str:
        """
        Normalize variable names for renaming resistance.

        Args:
            var_name: Original variable name

        Returns:
            Normalized variable name
        """
        if not var_name:
            return "VAR"

        # Keep common patterns
        if var_name in ["i", "j", "k"]:
            return "LOOP_VAR"
        elif len(var_name) == 1 and var_name.isalpha():
            return "VAR"
        elif var_name in ["self", "this"]:
            return "SELF"
        elif var_name.startswith("__") and var_name.endswith("__"):
            return "MAGIC_VAR"
        elif var_name.isupper():
            return "CONST"
        elif var_name.startswith("_"):
            return "PRIVATE_VAR"
        else:
            # Generic variable
            return "VAR"

    def _normalize_literal(self, literal: str) -> str:
        """
        Normalize literals for better matching.

        Args:
            literal: Original literal value

        Returns:
            Normalized literal
        """
        if not literal:
            return "LITERAL"

        # Numbers
        if literal.isdigit() or (literal.startswith("-") and literal[1:].isdigit()):
            return "NUM"
        # Booleans
        elif literal.lower() in ["true", "false"]:
            return "BOOL"
        # None/null
        elif literal.lower() in ["none", "null", "nil", "undefined"]:
            return "NULL"
        # Strings
        elif (literal.startswith('"') and literal.endswith('"')) or (
            literal.startswith("'") and literal.endswith("'")
        ):
            return "STR"
        else:
            return "LITERAL"

    def _get_adaptive_k(self, tokens: list[dict[str, Any]]) -> int:
        """
        Get adaptive k-gram size based on code length and complexity.

        Args:
            tokens: List of tokens

        Returns:
            Optimal k-gram size
        """
        if not self.adaptive:
            return self.k or 5

        num_tokens = len(tokens)

        # Adaptive sizing based on code length
        if num_tokens < 50:
            return 3  # Small code, small k-grams
        elif num_tokens < 200:
            return 5  # Medium code
        elif num_tokens < 500:
            return 9  # Large code
        else:
            return 15  # Very large code

    def _get_adaptive_t(self, k: int) -> int:
        """
        Get adaptive window size based on k-gram size.

        Args:
            k: K-gram size

        Returns:
            Optimal window size
        """
        # Window size should be larger than k-gram size
        # Rule of thumb: t = k * 2
        return max(k * 2, 4)

    def _multi_pass_compare(
        self, tokens_a: list[dict[str, Any]], tokens_b: list[dict[str, Any]]
    ) -> float:
        """
        Perform multi-pass comparison with multiple k-gram sizes.

        Args:
            tokens_a: First normalized tokens
            tokens_b: Second normalized tokens

        Returns:
            Combined similarity score
        """
        similarities = []
        weights = []

        for k in self.k_sizes:
            t = self._get_adaptive_t(k)

            # Generate fingerprints with this k-gram size
            fp_a = self._get_winnowing_fingerprint(tokens_a, k, t)
            fp_b = self._get_winnowing_fingerprint(tokens_b, k, t)

            # Calculate similarity
            sim = self._jaccard_similarity(fp_a, fp_b)

            # Weight smaller k-grams higher (more sensitive to changes)
            weight = 1.0 / (k**0.5)

            similarities.append(sim)
            weights.append(weight)

        # Weighted average
        if sum(weights) == 0:
            return 0.0

        weighted_sum = sum(s * w for s, w in zip(similarities, weights))
        total_weight = sum(weights)

        return weighted_sum / total_weight

    def _single_pass_compare(
        self, tokens_a: list[dict[str, Any]], tokens_b: list[dict[str, Any]]
    ) -> float:
        """
        Perform single-pass comparison.

        Args:
            tokens_a: First normalized tokens
            tokens_b: Second normalized tokens

        Returns:
            Similarity score
        """
        k = self.k or self._get_adaptive_k(tokens_a)
        t = self.t or self._get_adaptive_t(k)

        fp_a = self._get_winnowing_fingerprint(tokens_a, k, t)
        fp_b = self._get_winnowing_fingerprint(tokens_b, k, t)

        return self._jaccard_similarity(fp_a, fp_b)

    def _get_winnowing_fingerprint(
        self, tokens: list[dict[str, Any]], k: int, t: int
    ) -> list[str]:
        """
        Generate a winnowing fingerprint from tokens.

        Args:
            tokens: List of normalized tokens
            k: K-gram size
            t: Window size

        Returns:
            List of fingerprint hashes
        """
        if len(tokens) < k:
            if tokens:
                return [self._hash_tokens(tokens)]
            return []

        cache_key = (hash(tuple((t["value"], t.get("weight", 1.0)) for t in tokens)), k, t, self.weighted)
        with self._cache_lock:
            cached = self._fp_cache.get(cache_key)
            if cached is not None:
                self._fp_cache.move_to_end(cache_key)
                return cached
        fingerprints = self._compute_fingerprint(tokens, k, t)
        with self._cache_lock:
            self._fp_cache[cache_key] = fingerprints
            while len(self._fp_cache) > _CACHE_SIZE:
                self._fp_cache.popitem(last=False)
        return fingerprints

    def _compute_fingerprint(self, tokens: list[dict[str, Any]], k: int, t: int) -> list[str]:
        """Winnowing fingerprint of ``tokens`` (uncached)."""
        # Generate k-grams with weights
        k_grams = []
        for i in range(len(tokens) - k + 1):
            k_gram = tokens[i : i + k]
            k_grams.append(k_gram)

        # Hash k-grams (weighted if enabled)
        hashes = []
        for k_gram in k_grams:
            if self.weighted:
                hash_val = self._weighted_hash_tokens(k_gram)
            else:
                hash_val = self._hash_tokens(k_gram)
            hashes.append(hash_val)

        # Apply winnowing algorithm
        fingerprints = self._winnow(hashes, t)

        return fingerprints

    def _hash_tokens(self, tokens: list[dict[str, Any]]) -> str:
        """
        Hash a list of tokens.

        Args:
            tokens: List of token dictionaries

        Returns:
            Hexadecimal hash string
        """
        # Concatenate token values
        text = " ".join(t["value"] for t in tokens)
        return hashlib.blake2b(text.encode("utf-8"), digest_size=8).hexdigest()

    def _weighted_hash_tokens(self, tokens: list[dict[str, Any]]) -> str:
        """
        Hash tokens with weights applied.

        Args:
            tokens: List of token dictionaries with weights

        Returns:
            Weighted hexadecimal hash string
        """
        # Build weighted string
        parts = []
        for token in tokens:
            weight = token.get("weight", 1.0)
            value = token["value"]

            # Repeat high-weight tokens for emphasis
            repeat = max(1, int(weight))
            parts.extend([value] * repeat)

        text = " ".join(parts)
        return hashlib.blake2b(text.encode("utf-8"), digest_size=8).hexdigest()

    def _winnow(self, hashes: list[str], t: int) -> list[str]:
        """
        Apply the winnowing algorithm to select fingerprints.

        Args:
            hashes: List of hash values
            t: Window size

        Returns:
            Selected fingerprints
        """
        if len(hashes) < t:
            return hashes

        fingerprints = []
        last_min_pos = -1

        for i in range(len(hashes) - t + 1):
            window = hashes[i : i + t]
            min_hash = min(window)
            min_pos = i + window.index(min_hash)

            # Only add if min hash position is new
            if min_pos != last_min_pos:
                fingerprints.append(min_hash)
                last_min_pos = min_pos

        return fingerprints

    def _jaccard_similarity(self, set_a: list[str], set_b: list[str]) -> float:
        """
        Calculate Jaccard similarity between two lists.

        Args:
            set_a: First list
            set_b: Second list

        Returns:
            Jaccard similarity coefficient
        """
        if not set_a and not set_b:
            return 1.0
        if not set_a or not set_b:
            return 0.0

        set_a_set = set(set_a)
        set_b_set = set(set_b)

        intersection = len(set_a_set.intersection(set_b_set))
        union = len(set_a_set.union(set_b_set))

        if union == 0:
            return 0.0

        return intersection / union

    def _control_flow_similarity(
        self,
        parsed_a: dict,
        parsed_b: dict,
        tokens_a: list[dict] | None = None,
        tokens_b: list[dict] | None = None,
    ) -> float | None:
        """
        Calculate control flow similarity between two code samples.

        Args:
            parsed_a: First parsed code
            parsed_b: Second parsed code
            tokens_a: Token dicts to read instead of ``parsed_a["tokens"]``
            tokens_b: Token dicts to read instead of ``parsed_b["tokens"]``

        Returns:
            Multiset-Jaccard similarity of the control-flow constructs, or ``None``
            when NEITHER file has any (no evidence either way; it was 1.0).
        """
        cf_a = self._extract_control_flow(parsed_a, tokens_a)
        cf_b = self._extract_control_flow(parsed_b, tokens_b)

        if not cf_a and not cf_b:
            return None
        if not cf_a or not cf_b:
            return 0.0

        count_a, count_b = Counter(cf_a), Counter(cf_b)
        union = sum((count_a | count_b).values())
        return sum((count_a & count_b).values()) / union if union else 0.0

    def _extract_control_flow(self, parsed: dict, tokens: list[dict] | None = None) -> list[str]:
        """
        Extract control flow patterns from parsed code.

        Args:
            parsed: Parsed code representation
            tokens: Token dicts to read instead of ``parsed["tokens"]``

        Returns:
            List of control flow patterns
        """
        patterns = []
        if tokens is None:
            tokens = parsed.get("tokens", [])

        for token in tokens:
            token_type = token.get("type", "")
            value = token.get("value", "")

            if token_type == "KEYWORD":
                if value in ("if", "elif", "else", "switch", "case"):
                    patterns.append("CONDITIONAL")
                elif value in ("for", "while", "do"):
                    patterns.append("LOOP")
                elif value == "return":
                    patterns.append("RETURN")
                elif value in ("try", "except", "catch", "finally"):
                    patterns.append("EXCEPTION")
                elif value in ("break", "continue"):
                    patterns.append("LOOP_CONTROL")
                elif value in _FUNCTION_WORDS:
                    patterns.append("FUNCTION_DEF")  # raw-tokenised input marks ``def`` as KEYWORD
                elif value == "class":
                    patterns.append("CLASS_DEF")
            elif token_type == "FUNCTION":
                patterns.append("FUNCTION_DEF")
            elif token_type == "CLASS":
                patterns.append("CLASS_DEF")

        return patterns

    def _detect_ai_generated(self, parsed: dict) -> float:
        """
        Detect if code is likely AI-generated.

        Args:
            parsed: Parsed code representation

        Returns:
            AI detection score (0.0 = human, 1.0 = AI-generated)
        """
        if not self.ai_detection:
            return 0.0

        tokens = parsed.get("tokens", [])
        raw_code = parsed.get("raw", "")

        score = 0.0
        checks = 0

        # Check 1: Perplexity (variance in token types)
        token_types = [t.get("type", "") for t in tokens]
        type_counts = defaultdict(int)
        for t in token_types:
            type_counts[t] += 1

        if type_counts:
            # AI code tends to have more uniform distribution
            entropy = self._calculate_entropy(list(type_counts.values()))
            # Lower entropy = more likely AI
            if entropy < 2.0:
                score += 0.3
            checks += 1

        # Check 2: Burstiness (variance in sentence/token length)
        if tokens:
            lengths = [len(t.get("value", "")) for t in tokens]
            if lengths:
                mean_len = sum(lengths) / len(lengths)
                variance = sum((line - mean_len) ** 2 for line in lengths) / len(lengths)
                # Lower variance = more likely AI
                if variance < 10:
                    score += 0.2
                checks += 1

        # Check 3: Pattern repetition
        if tokens:
            patterns = [t.get("value", "") for t in tokens[:50]]
            unique_patterns = len(set(patterns))
            repetition_ratio = 1 - (unique_patterns / len(patterns))
            # Higher repetition = more likely AI
            if repetition_ratio > 0.3:
                score += 0.2
            checks += 1

        # Check 4: Comment style
        comment_tokens = [t for t in tokens if t.get("type") == "COMMENT"]
        if comment_tokens:
            # AI tends to add more comments
            comment_ratio = len(comment_tokens) / len(tokens)
            if comment_ratio > 0.1:
                score += 0.15
            checks += 1

        # Check 5: AI patterns in raw code
        for pattern in self.ai_patterns:
            if re.search(pattern, raw_code, re.IGNORECASE):
                score += 0.15
                checks += 1
                break

        # Normalize score
        if checks > 0:
            return min(1.0, score)

        return 0.0

    def _calculate_entropy(self, values: list[int]) -> float:
        """
        Calculate Shannon entropy of a distribution.

        Args:
            values: List of counts

        Returns:
            Entropy value
        """
        total = sum(values)
        if total == 0:
            return 0.0

        entropy = 0.0
        for count in values:
            if count > 0:
                p = count / total
                entropy -= p * math.log2(p)

        return entropy
