#!/usr/bin/env bash
# =============================================================================
# IntegrityDesk - Production Setup
# One-time install for a fresh server:
#   - creates the run-as user
#   - builds the Python venv + installs dependencies
#   - generates src/backend/.env.local from deploy.conf
#   - builds the Next.js dashboard
#   - installs systemd units, nginx site, and a Let's Encrypt cert
#   - starts everything
#
#   sudo bash deploy/setup.sh
#
# Run bootstrap.sh first (installs OS packages). This script is idempotent.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

CONF_FILE="$SCRIPT_DIR/deploy.conf"
CONF_EXAMPLE="$SCRIPT_DIR/deploy.conf.example"

log() { echo -e "\033[1;32m[setup]\033[0m $*"; }
warn() { echo -e "\033[1;33m[setup WARN]\033[0m $*"; }
die() { echo -e "\033[1;31m[setup ERROR]\033[0m $*" >&2; exit 1; }

# -----------------------------------------------------------------------------
# Load config
# -----------------------------------------------------------------------------
[ -f "$CONF_FILE" ] || die "Missing $CONF_FILE. Run:
  cp $CONF_EXAMPLE $CONF_FILE
and edit it first."

# shellcheck disable=SC1090
source "$CONF_FILE"

APP_DOMAIN="${APP_DOMAIN:-}"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-admin@$(hostname)}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3000}"
BACKEND_PORT="${BACKEND_PORT:-8000}"
EMBEDDING_PORT="${EMBEDDING_PORT:-8001}"
DATABASE_URL="${DATABASE_URL:-}"
REDIS_URL="${REDIS_URL:-redis://127.0.0.1:6379/0}"
APP_DIR="${APP_DIR:-$REPO_DIR}"
RUN_USER="${RUN_USER:-${SUDO_USER:-$(whoami)}}"
WEB_SERVER="${WEB_SERVER:-apache}"
SKIP_VENV="${SKIP_VENV:-0}"

# Normalize APP_DIR to an absolute path
APP_DIR="$(realpath -m "$APP_DIR")"

[ -n "$APP_DOMAIN" ] || die "APP_DOMAIN is not set in deploy.conf"
[ -n "$DATABASE_URL" ] || die "DATABASE_URL is not set in deploy.conf"
case "$DATABASE_URL" in
    sqlite*) die "SQLite is not supported for the backend runtime. Use a PostgreSQL URL." ;;
    postgres*) : ;;
    *) warn "DATABASE_URL does not look like a PostgreSQL URL: $DATABASE_URL" ;;
esac

[ "$(id -u)" -eq 0 ] || die "Run as root: sudo bash deploy/setup.sh"

log "Configuration:"
log "  APP_DIR=$APP_DIR  RUN_USER=$RUN_USER  DOMAIN=$APP_DOMAIN"
log "  backend=$BACKEND_PORT  dashboard=$DASHBOARD_PORT  embedding=$EMBEDDING_PORT"
log "  web_server=$WEB_SERVER  skip_venv=$SKIP_VENV"

# -----------------------------------------------------------------------------
# Run-as user
# -----------------------------------------------------------------------------
if [ "$RUN_USER" != "root" ] && ! id -u "$RUN_USER" >/dev/null 2>&1; then
    log "Creating system user '$RUN_USER'..."
    useradd --system --home-dir "$APP_DIR" --shell /usr/sbin/nologin "$RUN_USER"
fi

if [ "$RUN_USER" != "root" ]; then
    chown -R "$RUN_USER":"$RUN_USER" "$APP_DIR" 2>/dev/null || warn "Could not chown $APP_DIR"
fi

# -----------------------------------------------------------------------------
# Python venv + dependencies
# -----------------------------------------------------------------------------
if [ "$SKIP_VENV" = "1" ]; then
    [ -x "$APP_DIR/venv/bin/python" ] || die "SKIP_VENV=1 but no venv found at $APP_DIR/venv"
    log "Skipping venv creation (SKIP_VENV=1), using existing venv at $APP_DIR/venv"
else
    log "Creating virtualenv..."
    python3 -m venv "$APP_DIR/venv"
    "$APP_DIR/venv/bin/pip" install --upgrade pip
fi
log "Installing Python dependencies (this may take a few minutes)..."
"$APP_DIR/venv/bin/pip" install -r "$APP_DIR/requirements.txt"

# -----------------------------------------------------------------------------
# Generate secrets + .env.local
# -----------------------------------------------------------------------------
AUTH_JWT_SECRET="${AUTH_JWT_SECRET:-$(openssl rand -hex 32)}"
WEBHOOK_SECRET_KEY="${WEBHOOK_SECRET_KEY:-$(openssl rand -hex 32)}"

ENV_FILE="$APP_DIR/src/backend/.env.local"
BACKEND_URL="http://127.0.0.1:$BACKEND_PORT"
FRONTEND_URL="https://$APP_DOMAIN"

log "Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy/setup.sh - do not edit by hand
APP_NAME=IntegrityDesk
APP_ENV=production
DEBUG=false
HOST=127.0.0.1
PORT=$BACKEND_PORT
BACKEND_URL=$BACKEND_URL
FRONTEND_URL=$FRONTEND_URL
AUTH_JWT_SECRET=$AUTH_JWT_SECRET
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
# Session cookies are served over HTTPS (certbot TLS), so mark them Secure.
AUTH_COOKIE_SECURE=true
WEBHOOK_SECRET_KEY=$WEBHOOK_SECRET_KEY
DATABASE_URL=$DATABASE_URL
DATABASE_POOL_SIZE=10
DATABASE_MAX_OVERFLOW=20
REDIS_URL=$REDIS_URL
CORS_ALLOWED_ORIGINS=$FRONTEND_URL
OPENAI_API_KEY=${OPENAI_API_KEY:-}
EMBEDDING_SERVER_URL=${EMBEDDING_SERVER_URL:-}
EMBEDDING_SERVER_HOST=${EMBEDDING_SERVER_HOST:-}
EMBEDDING_SERVER_PORT=$EMBEDDING_PORT
LOG_LEVEL=INFO
UPLOAD_DIR=./uploads
MAX_UPLOAD_SIZE_MB=100
EOF

# -----------------------------------------------------------------------------
# Initialize database (create tables if they don't exist)
# -----------------------------------------------------------------------------
log "Initializing database schema..."
(cd "$APP_DIR" && "$APP_DIR/venv/bin/python" -c "from src.backend.config.database import init_db; init_db()") \
    || die "Database init failed. Check DATABASE_URL connectivity."

# -----------------------------------------------------------------------------
# Build Next.js dashboard
# -----------------------------------------------------------------------------
if ! command -v node >/dev/null 2>&1; then
    die "Node.js is not installed. Run: sudo bash deploy/bootstrap.sh"
fi
log "Installing frontend dependencies..."
(
    cd "$APP_DIR/src/frontend"
    npm install --no-audit --no-fund
)
log "Building Next.js dashboard (this can take a few minutes)..."
(
    cd "$APP_DIR/src/frontend"
    API_URL="$BACKEND_URL" NEXT_PUBLIC_API_URL="$BACKEND_URL" npm run build
)

# -----------------------------------------------------------------------------
# systemd units
# -----------------------------------------------------------------------------
log "Installing systemd units..."
SERVICES_DIR="$SCRIPT_DIR/systemd"

install_service() {
    local src="$1"
    local svc
    svc="$(basename "$src")"
    sed \
        -e "s|@APP_DIR@|$APP_DIR|g" \
        -e "s|@RUN_USER@|$RUN_USER|g" \
        -e "s|@BACKEND_PORT@|$BACKEND_PORT|g" \
        -e "s|@EMBEDDING_PORT@|$EMBEDDING_PORT|g" \
        -e "s|@DASHBOARD_PORT@|$DASHBOARD_PORT|g" \
        "$src" > "/etc/systemd/system/$svc"
    log "  installed /etc/systemd/system/$svc"
}

install_service "$SERVICES_DIR/integritydesk-backend.service"
install_service "$SERVICES_DIR/integritydesk-dashboard.service"
install_service "$SERVICES_DIR/integritydesk-worker.service"

# Embedding server only if the ML stack is enabled
if [ -n "${EMBEDDING_SERVER_URL:-}" ]; then
    install_service "$SERVICES_DIR/integritydesk-embedding.service"
fi

systemctl daemon-reload

# -----------------------------------------------------------------------------
# Web server + TLS (apache or nginx)
# -----------------------------------------------------------------------------
if [ "$WEB_SERVER" = "apache" ]; then
    log "Configuring Apache..."
    sed \
        -e "s|@APP_DOMAIN@|$APP_DOMAIN|g" \
        -e "s|@DASHBOARD_PORT@|$DASHBOARD_PORT|g" \
        -e "s|@BACKEND_PORT@|$BACKEND_PORT|g" \
        "$SCRIPT_DIR/apache/integritydesk.conf" \
        > "/etc/apache2/sites-available/integritydesk.conf"

    a2ensite integritydesk >/dev/null 2>&1 || true
    a2dissite 000-default >/dev/null 2>&1 || true
    a2enmod proxy proxy_http proxy_wstunnel rewrite headers ssl >/dev/null 2>&1 || true

    apache2ctl configtest || die "Apache config test failed"
    systemctl enable apache2
    systemctl reload apache2

    if [ -n "$CERTBOT_EMAIL" ]; then
        log "Requesting Let's Encrypt certificate for $APP_DOMAIN..."
        certbot --apache -d "$APP_DOMAIN" --non-interactive --agree-tos -m "$CERTBOT_EMAIL" \
            || warn "certbot failed. The site will run on HTTP only; re-run: sudo certbot --apache -d $APP_DOMAIN"
        systemctl reload apache2
    else
        warn "CERTBOT_EMAIL not set - serving HTTP only. Run certbot manually to enable TLS."
    fi
else
    log "Configuring nginx..."
    sed \
        -e "s|@APP_DOMAIN@|$APP_DOMAIN|g" \
        -e "s|@DASHBOARD_PORT@|$DASHBOARD_PORT|g" \
        -e "s|@BACKEND_PORT@|$BACKEND_PORT|g" \
        "$SCRIPT_DIR/nginx/integritydesk.conf" \
        > "/etc/nginx/sites-available/integritydesk"

    if [ -f "/etc/nginx/sites-enabled/default" ]; then
        rm -f /etc/nginx/sites-enabled/default
    fi
    ln -sf /etc/nginx/sites-available/integritydesk /etc/nginx/sites-enabled/integritydesk

    nginx -t || die "nginx config test failed"
    systemctl enable nginx
    systemctl reload nginx

    if [ -n "$CERTBOT_EMAIL" ]; then
        log "Requesting Let's Encrypt certificate for $APP_DOMAIN..."
        certbot --nginx -d "$APP_DOMAIN" --non-interactive --agree-tos -m "$CERTBOT_EMAIL" \
            || warn "certbot failed. The site will run on HTTP only; re-run: sudo certbot --nginx -d $APP_DOMAIN"
        systemctl reload nginx
    else
        warn "CERTBOT_EMAIL not set - serving HTTP only. Run certbot manually to enable TLS."
    fi
fi

# -----------------------------------------------------------------------------
# Start services
# -----------------------------------------------------------------------------
log "Starting services..."
systemctl enable integritydesk-backend integritydesk-dashboard integritydesk-worker
systemctl restart integritydesk-backend integritydesk-dashboard integritydesk-worker
if [ -n "${EMBEDDING_SERVER_URL:-}" ]; then
    systemctl enable integritydesk-embedding
    systemctl restart integritydesk-embedding
fi

sleep 3

log "Service status:"
systemctl --no-pager --full status integritydesk-backend integritydesk-dashboard integritydesk-worker \
    | grep -E "Loaded:|Active:" || true

log ""
log "Setup complete."
log "  Dashboard: https://$APP_DOMAIN"
log "  Backend:   $BACKEND_URL (docs at $BACKEND_URL/docs)"
log ""
log "Manage with:  sudo systemctl status|restart integritydesk-{backend,dashboard,worker}"
log "After future 'git pull', run:  sudo bash $SCRIPT_DIR/update.sh"
