"""AI-Generated Code Detection Engine.

Detects code likely generated by LLMs (ChatGPT, Claude, Copilot, etc.)
using multiple detection strategies:
- XGBoost / RandomForest classifier on 29 dimensional stylometry features
- Perplexity scoring (surprise factor)
- Burstiness analysis (variation in sentence length/complexity)
- Pattern repetition detection

Usage:
    from src.engines.similarity.ai_detection import AIDetectionEngine
    detector = AIDetectionEngine()
    result = detector.analyze(code_snippet)
    print(f"AI probability: {result['ai_probability']:.2%}")
"""

import logging
import math
import re
import pickle
import os
from typing import Any, Dict, List, Optional, Tuple
from pathlib import Path

try:
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score, roc_auc_score

    HAS_SKLEARN = True
except ImportError:
    HAS_SKLEARN = False

try:
    import xgboost as xgb

    HAS_XGBOOST = True
except ImportError:
    HAS_XGBOOST = False

from src.engines.features.code_stylometry import StylometryExtractor, StylometryFeatures

logger = logging.getLogger(__name__)


class AIDetectionEngine:
    """Multi-strategy AI-generated code detector.

    Combines multiple signals to identify LLM-generated code:
    1. Perplexity: LLMs produce "surprising" code patterns
    2. Burstiness: Human code has more variation in complexity
    3. Stylometry: Comment patterns, naming conventions
    4. Pattern repetition: LLMs tend to repeat certain patterns
    """

    def __init__(
        self, perplexity_threshold: float = 0.7, burstiness_threshold: float = 0.6
    ) -> None:
        """Initialize AI detection engine.

        Args:
            perplexity_threshold: Threshold for perplexity-based detection (0-1)
            burstiness_threshold: Threshold for burstiness-based detection (0-1)
        """
        self.perplexity_threshold = perplexity_threshold
        self.burstiness_threshold = burstiness_threshold

        # Common LLM patterns (heuristics)
        self.llm_patterns = [
            r"(?i)#\s*(let|we)\s+(us|me)\s+",  # "Let us..." pattern
            r"(?i)#\s*(here|this)\s+is\s+",  # "Here is..." pattern
            r'(?i)def\s+\w+[^:]*:\s*"""',  # Docstring immediately after def
            r"(?i)#\s*[A-Z][a-z]+(?:\s+[a-z]+)*\s*$",  # Title-case comments
            r"(?i)(import\s+[\w.]+\s+as\s+\w+\s*){3,}",  # Multiple aliased imports
        ]

        # Common LLM naming patterns
        self.llm_naming_patterns = [
            r"\b(result|output|data|value|temp|final|new)\b",  # Generic names
            r"\b(process_|handle_|compute_|calculate_)\w+",  # Verb_ prefixes
        ]

    def analyze(self, code: str, language: str = "python") -> Dict[str, Any]:
        """Analyze code for AI-generated patterns.

        Args:
            code: Source code to analyze
            language: Programming language (python, java, cpp, etc.)

        Returns:
            Dictionary with detection results:
            - ai_probability: Overall probability (0-1)
            - signals: Individual signal scores
            - confidence: Detection confidence (0-1)
            - indicators: List of detected indicators
        """
        if not code or len(code.strip()) < 20:
            return {
                "ai_probability": 0.0,
                "confidence": 0.0,
                "signals": {},
                "indicators": [],
                "error": "Code too short for analysis",
            }

        try:
            # Calculate individual signals
            signals = {
                "perplexity": self._calculate_perplexity(code),
                "burstiness": self._calculate_burstiness(code),
                "stylometry": self._calculate_stylometry(code),
                "pattern_repetition": self._calculate_pattern_repetition(code),
            }

            # Combine signals with learned weights
            heuristic_probability = self._combine_signals(signals)
            heuristic_confidence = self._calculate_confidence(signals)

            # Run ML classifier if available
            ml_result = self.predict_ml(code)
            if ml_result is not None:
                ml_probability, ml_confidence = ml_result

                # Weighted combination: prefer ML when confident
                if ml_confidence > 0.7:
                    ai_probability = 0.7 * ml_probability + 0.3 * heuristic_probability
                    confidence = max(ml_confidence, heuristic_confidence)
                else:
                    ai_probability = 0.4 * ml_probability + 0.6 * heuristic_probability
                    confidence = 0.5 * ml_confidence + 0.5 * heuristic_confidence
            else:
                ai_probability = heuristic_probability
                confidence = heuristic_confidence

            # Identify specific indicators
            indicators = self._identify_indicators(code)

            return {
                "ai_probability": ai_probability,
                "confidence": confidence,
                "signals": signals,
                "indicators": indicators,
                "language": language,
            }

        except Exception as exc:
            logger.error(f"AI detection failed: {exc}")
            return {
                "ai_probability": 0.0,
                "confidence": 0.0,
                "signals": {},
                "indicators": [],
                "error": str(exc),
            }

    def _calculate_perplexity(self, code: str) -> float:
        """Calculate perplexity-based AI score.

        LLM-generated code tends to have lower perplexity (more predictable)
        when evaluated by a language model trained on human code.

        Returns:
            Score between 0 (human-like) and 1 (AI-like)
        """
        try:
            # Simplified perplexity using token frequency analysis
            tokens = self._tokenize_code(code)
            if not tokens:
                return 0.0

            # Calculate token frequency distribution
            freq_dist = {}
            for token in tokens:
                freq_dist[token] = freq_dist.get(token, 0) + 1

            # Calculate entropy (lower entropy = more predictable = more AI-like)
            total = len(tokens)
            entropy = 0.0
            for freq in freq_dist.values():
                p = freq / total
                if p > 0:
                    entropy -= p * math.log2(p)

            # Normalize entropy (typical range: 3-8 for code)
            normalized_entropy = max(0, min(1, (entropy - 3) / 5))

            # Lower entropy = higher AI probability
            return 1.0 - normalized_entropy

        except Exception as exc:
            logger.debug(f"Perplexity calculation failed: {exc}")
            return 0.0

    def _calculate_burstiness(self, code: str) -> float:
        """Calculate burstiness (variation in complexity).

        Human code has more variation in line length and complexity.
        AI code tends to be more uniform.

        Returns:
            Score between 0 (human-like variation) and 1 (AI-like uniformity)
        """
        try:
            lines = [line.strip() for line in code.split("\n") if line.strip()]
            if len(lines) < 3:
                return 0.0

            # Calculate line complexity (length + nesting depth)
            complexities = []
            for line in lines:
                length_score = len(line) / 100.0  # Normalize by 100 chars
                indent_level = len(line) - len(line.lstrip())
                nesting_score = indent_level / 4.0  # Assume 4-space indentation
                complexity = length_score + nesting_score
                complexities.append(complexity)

            # Calculate coefficient of variation (CV)
            mean = sum(complexities) / len(complexities)
            if mean == 0:
                return 0.0

            variance = sum((c - mean) ** 2 for c in complexities) / len(complexities)
            std_dev = math.sqrt(variance)
            cv = std_dev / mean

            # Lower CV = more uniform = more AI-like
            # Typical CV for human code: 0.5-1.5
            normalized_cv = max(0, min(1, cv / 1.5))
            return 1.0 - normalized_cv

        except Exception as exc:
            logger.debug(f"Burstiness calculation failed: {exc}")
            return 0.0

    def _calculate_stylometry(self, code: str) -> float:
        """Calculate stylometric AI score.

        Analyzes writing style patterns that differ between humans and LLMs.

        Returns:
            Score between 0 (human-like) and 1 (AI-like)
        """
        try:
            ai_score = 0.0
            total_checks = 0

            # Check 1: Comment patterns
            comment_lines = [
                line.strip()
                for line in code.split("\n")
                if line.strip().startswith("#") or line.strip().startswith("//")
            ]

            if comment_lines:
                # LLMs tend to write more formal, complete sentence comments
                formal_patterns = [
                    r"^#\s+[A-Z][a-z]+(?:\s+[a-z]+)*\s*$",  # Title case
                    r"^#\s+(This|The|Let|We|Here|Note)\s+",  # Formal starters
                ]
                formal_count = sum(
                    1
                    for comment in comment_lines
                    for pattern in formal_patterns
                    if re.match(pattern, comment)
                )
                if len(comment_lines) > 0:
                    formal_ratio = formal_count / len(comment_lines)
                    ai_score += formal_ratio
                    total_checks += 1

            # Check 2: Naming conventions
            # LLMs tend to use more generic/verbose names
            generic_names = len(
                re.findall(
                    r"\b(result|output|data|value|temp|final|new|process_|handle_)\w*\b",
                    code,
                )
            )
            total_identifiers = len(re.findall(r"\b[a-zA-Z_]\w*\b", code))
            if total_identifiers > 0:
                generic_ratio = generic_names / total_identifiers
                ai_score += generic_ratio
                total_checks += 1

            # Check 3: Function length uniformity
            functions = re.findall(r"def\s+\w+\s*\([^)]*\)\s*:", code)
            if len(functions) >= 2:
                # Check if all functions have similar structure (AI tendency)
                func_lengths = [len(func) for func in functions]
                if func_lengths:
                    mean_len = sum(func_lengths) / len(func_lengths)
                    if mean_len > 0:
                        variance = sum((l - mean_len) ** 2 for l in func_lengths) / len(
                            func_lengths
                        )
                        cv = math.sqrt(variance) / mean_len
                        ai_score += 1.0 - min(1.0, cv)
                        total_checks += 1

            return ai_score / total_checks if total_checks > 0 else 0.0

        except Exception as exc:
            logger.debug(f"Stylometry calculation failed: {exc}")
            return 0.0

    def _calculate_pattern_repetition(self, code: str) -> float:
        """Calculate pattern repetition score.

        LLMs tend to repeat certain code patterns more frequently than humans.

        Returns:
            Score between 0 (human-like) and 1 (AI-like)
        """
        try:
            # Check for LLM-specific patterns
            pattern_matches = 0
            for pattern in self.llm_patterns:
                matches = len(re.findall(pattern, code))
                pattern_matches += matches

            # Check for repeated code structures
            # Split code into blocks and look for similar blocks
            lines = code.split("\n")
            block_size = 5
            blocks = []
            for i in range(0, len(lines) - block_size, block_size):
                block = "\n".join(lines[i : i + block_size]).strip()
                if block:
                    blocks.append(block)

            # Count duplicate blocks
            if blocks:
                unique_blocks = len(set(blocks))
                duplication_ratio = 1.0 - (unique_blocks / len(blocks))
            else:
                duplication_ratio = 0.0

            # Combine pattern matches and duplication
            pattern_score = min(1.0, pattern_matches / 5.0)  # Normalize
            combined_score = (pattern_score + duplication_ratio) / 2.0

            return combined_score

        except Exception as exc:
            logger.debug(f"Pattern repetition calculation failed: {exc}")
            return 0.0

    def _combine_signals(self, signals: Dict[str, float]) -> float:
        """Combine detection signals into overall AI probability.

        Uses weighted combination based on signal importance.
        Weights can be learned from labeled data.

        Returns:
            Overall AI probability (0-1)
        """
        # Learned weights (could be optimized with ML)
        weights = {
            "perplexity": 0.3,
            "burstiness": 0.25,
            "stylometry": 0.25,
            "pattern_repetition": 0.2,
        }

        total_score = 0.0
        total_weight = 0.0

        for signal, weight in weights.items():
            if signal in signals:
                total_score += signals[signal] * weight
                total_weight += weight

        return total_score / total_weight if total_weight > 0 else 0.0

    def _calculate_confidence(self, signals: Dict[str, float]) -> float:
        """Calculate confidence in the detection.

        Confidence is higher when signals agree with each other.

        Returns:
            Confidence score (0-1)
        """
        if not signals:
            return 0.0

        values = list(signals.values())
        if len(values) < 2:
            return 0.5

        # Calculate agreement (inverse of variance)
        mean = sum(values) / len(values)
        variance = sum((v - mean) ** 2 for v in values) / len(values)
        std_dev = math.sqrt(variance)

        # Lower std_dev = higher agreement = higher confidence
        confidence = 1.0 - min(1.0, std_dev * 2)

        # Boost confidence if we have more signals
        signal_count_bonus = min(0.2, len(values) * 0.05)

        return min(1.0, confidence + signal_count_bonus)

    def _identify_indicators(self, code: str) -> List[str]:
        """Identify specific AI indicators in the code.

        Returns:
            List of detected indicator descriptions
        """
        indicators = []

        # Check for LLM patterns
        for pattern in self.llm_patterns:
            matches = re.findall(pattern, code)
            if matches:
                indicators.append(f"Found {len(matches)} LLM-like patterns")
                break

        # Check for generic naming
        generic_count = len(
            re.findall(r"\b(result|output|data|value|temp|final|new)\b", code)
        )
        if generic_count > 3:
            indicators.append(
                f"High use of generic names ({generic_count} occurrences)"
            )

        # Check for uniform function structure
        functions = re.findall(r"def\s+\w+\s*\([^)]*\)\s*:", code)
        if len(functions) >= 3:
            func_lengths = [len(func) for func in functions]
            if func_lengths:
                mean_len = sum(func_lengths) / len(func_lengths)
                if mean_len > 0:
                    variance = sum((l - mean_len) ** 2 for l in func_lengths) / len(
                        func_lengths
                    )
                    cv = math.sqrt(variance) / mean_len
                    if cv < 0.3:
                        indicators.append("Functions have unusually uniform structure")

        # Check for excessive comments
        lines = code.split("\n")
        comment_lines = [
            l for l in lines if l.strip().startswith("#") or l.strip().startswith("//")
        ]
        if lines and len(comment_lines) / len(lines) > 0.3:
            indicators.append("Unusually high comment density")

        return indicators

    def _tokenize_code(self, code: str) -> List[str]:
        """Simple tokenizer for code.

        Splits code into tokens (identifiers, keywords, operators, etc.)
        """
        # Simple regex-based tokenization
        token_pattern = r"\b\w+\b|[+\-*/=<>!&|]+|[{}()\[\],;:]"
        tokens = re.findall(token_pattern, code)
        return [t.lower() for t in tokens if t]

    # === ML Classifier Methods ===
    def _extract_feature_vector(self, code: str) -> Optional[List[float]]:
        """Extract 29 dimensional stylometry feature vector from code."""
        try:
            features = self.stylometry_extractor.extract(code)
            return features.to_vector()
        except Exception as exc:
            logger.debug(f"Feature extraction failed: {exc}")
            return None

    def train_classifier(
        self,
        X: List[List[float]],
        y: List[int],
        test_size: float = 0.2,
        random_state: int = 42,
    ) -> Dict[str, Any]:
        """Train RandomForest classifier with holdout validation.

        Args:
            X: List of 29-dimensional feature vectors
            y: List of labels (0 = human, 1 = AI)
            test_size: Fraction of data to use for validation
            random_state: Random seed for reproducibility

        Returns:
            Dictionary with training metrics and model info
        """
        if not HAS_SKLEARN:
            raise ImportError("scikit-learn is required for training")

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=test_size, random_state=random_state, stratify=y
        )

        # Train RandomForest classifier
        self.classifier = RandomForestClassifier(
            n_estimators=200,
            max_depth=12,
            min_samples_split=5,
            min_samples_leaf=2,
            class_weight="balanced",
            random_state=random_state,
            n_jobs=-1,
        )

        self.classifier.fit(X_train, y_train)

        # Evaluate
        y_pred = self.classifier.predict(X_test)
        y_proba = self.classifier.predict_proba(X_test)[:, 1]

        metrics = {
            "accuracy": accuracy_score(y_test, y_pred),
            "roc_auc": roc_auc_score(y_test, y_proba),
            "test_size": len(X_test),
            "train_size": len(X_train),
            "feature_importance": dict(
                zip(
                    StylometryFeatures.feature_names(),
                    self.classifier.feature_importances_,
                )
            ),
        }

        self.feature_importance = metrics["feature_importance"]
        self.use_ml_classifier = True

        return metrics

    def predict_ml(self, code: str) -> Optional[Tuple[float, float]]:
        """Run ML classifier prediction on code.

        Returns:
            Tuple (ai_probability, confidence) or None if not available
        """
        if not self.use_ml_classifier or self.classifier is None:
            return None

        features = self._extract_feature_vector(code)
        if features is None:
            return None

        try:
            proba = self.classifier.predict_proba([features])[0]
            ai_prob = proba[1]
            confidence = max(proba)
            return (ai_prob, confidence)
        except Exception as exc:
            logger.debug(f"ML prediction failed: {exc}")
            return None

    def save_model(self, path: str) -> None:
        """Save trained model to file."""
        if self.classifier is None:
            raise ValueError("No trained model to save")

        with open(path, "wb") as f:
            pickle.dump(
                {
                    "classifier": self.classifier,
                    "feature_importance": self.feature_importance,
                    "version": "1.0",
                },
                f,
            )

    def _load_model(self, path: str) -> None:
        """Load pre-trained model from file."""
        try:
            with open(path, "rb") as f:
                data = pickle.load(f)
                self.classifier = data["classifier"]
                self.feature_importance = data.get("feature_importance")
            logger.debug(f"Loaded AI detection model from {path}")
        except Exception as exc:
            logger.warning(f"Failed to load model from {path}: {exc}")
            self.classifier = None
