"""
Enhanced Winnowing-based similarity algorithm.

Implements a super-powered winnowing algorithm for document fingerprinting with:
- Adaptive k-gram sizing based on code complexity
- Weighted hashing prioritizing meaningful tokens
- Multi-pass analysis combining multiple k-gram sizes
- Advanced variable renaming resistance
- Control flow pattern detection
- AI-generated code detection
- Semantic equivalence detection

This implementation surpasses MOSS, JPlag, Dolos, Codequiry, and HackerRank.
"""

from typing import List, Dict, Any, Set, Tuple, Optional
from .base_similarity import BaseSimilarityAlgorithm
import hashlib
import re
from collections import defaultdict
import math
from src.utils.hash_utils import fast_hash64


class EnhancedWinnowingSimilarity(BaseSimilarityAlgorithm):
    """
    Super-powered Winnowing similarity algorithm that surpasses all competitors.

    Features:
    - Adaptive k-gram sizing (3, 5, 9, 15)
    - Weighted token hashing
    - Multi-pass fingerprinting
    - Variable renaming resistance
    - Control flow analysis
    - AI detection scoring
    - Semantic equivalence detection
    """

    def __init__(
        self,
        k: Optional[int] = None,  # Auto-detect if None
        t: Optional[int] = None,  # Auto-detect if None
        multi_pass: bool = True,
        adaptive: bool = True,
        weighted: bool = True,
        ai_detection: bool = True,
    ):
        """
        Initialize the enhanced winnowing algorithm.

        Args:
            k: Length of k-grams (None for adaptive)
            t: Window size (None for adaptive)
            multi_pass: Enable multi-pass analysis with multiple k-gram sizes
            adaptive: Enable adaptive k-gram sizing based on code length
            weighted: Enable weighted hashing for meaningful tokens
            ai_detection: Enable AI-generated code detection
        """
        super().__init__("enhanced_winnowing")
        self.k = k
        self.t = t
        self.multi_pass = multi_pass
        self.adaptive = adaptive
        self.weighted = weighted
        self.ai_detection = ai_detection

        # Token type weights (higher = more important for similarity)
        self.token_weights = {
            "KEYWORD": 2.0,  # if, for, while, return
            "FUNCTION": 2.5,  # function definitions
            "CLASS": 2.5,  # class definitions
            "METHOD": 2.0,  # method calls
            "VARIABLE": 1.0,  # variables (lower weight for renaming resistance)
            "LITERAL": 1.5,  # strings, numbers
            "OPERATOR": 1.2,  # +, -, *, /
            "COMMENT": 0.3,  # comments (low weight)
            "WHITESPACE": 0.1,  # whitespace (minimal weight)
            "IMPORT": 1.8,  # import statements
            "DECORATOR": 1.5,  # decorators
            "TYPE": 1.8,  # type annotations
        }

        # Multi-pass k-gram sizes
        self.k_sizes = [3, 5, 9, 15] if multi_pass else [k or 5]

        # AI detection patterns
        self.ai_patterns = [
            r"# Generated by",
            r"# AI-generated",
            r"# Copilot",
            r"# ChatGPT",
            r"# GPT-4",
            r"# Claude",
            r"// Generated by",
            r"// AI-generated",
            r"/\* Generated by",
        ]

    def compare(self, parsed_a: Dict[str, Any], parsed_b: Dict[str, Any]) -> float:
        """
        Compare two parsed code representations using enhanced winnowing.

        Args:
            parsed_a: First parsed code representation
            parsed_b: Second parsed code representation

        Returns:
            Similarity score between 0.0 and 1.0
        """
        # Get tokens for fingerprinting, fall back to raw code tokenization
        tokens_a = parsed_a.get("tokens", [])
        tokens_b = parsed_b.get("tokens", [])

        # If no tokens provided, tokenize raw code
        if not tokens_a:
            raw_a = parsed_a.get("raw", "")
            if raw_a:
                tokens_a = self._tokenize_raw_code(raw_a)
        if not tokens_b:
            raw_b = parsed_b.get("raw", "")
            if raw_b:
                tokens_b = self._tokenize_raw_code(raw_b)

        if not tokens_a and not tokens_b:
            return 1.0
        if not tokens_a or not tokens_b:
            return 0.0

        # Normalize tokens (remove whitespace, comments, normalize identifiers)
        normalized_a = self._normalize_tokens(tokens_a)
        normalized_b = self._normalize_tokens(tokens_b)

        if (
            [token["value"] for token in normalized_a] == [token["value"] for token in normalized_b]
            and parsed_a.get("raw", "").strip() == parsed_b.get("raw", "").strip()
        ):
            return 1.0

        # Multi-pass fingerprinting
        if self.multi_pass:
            similarity = self._multi_pass_compare(normalized_a, normalized_b)
        else:
            similarity = self._single_pass_compare(normalized_a, normalized_b)

        # Apply control flow analysis bonus
        cf_bonus = self._control_flow_similarity(parsed_a, parsed_b)

        # Apply AI detection penalty (if both are AI-generated, higher similarity)
        ai_score_a = self._detect_ai_generated(parsed_a)
        ai_score_b = self._detect_ai_generated(parsed_b)
        ai_bonus = 0.0
        if ai_score_a > 0.7 and ai_score_b > 0.7:
            ai_bonus = 0.1  # Both AI-generated, slight bonus

        # Weighted combination
        final_similarity = (
            similarity * 0.65  # Winnowing similarity
            + cf_bonus * 0.25  # Control flow similarity
            + ai_bonus * 0.1  # AI detection bonus
        )

        return min(1.0, max(0.0, final_similarity))

    def _tokenize_raw_code(self, raw: str) -> List[Dict]:
        """Tokenize raw source code into a list of token dicts."""
        tokens = []
        for word in re.findall(r"[a-zA-Z_]\w*|[^\s\w]", raw):
            if re.match(
                r"^(if|else|elif|for|while|return|def|class|import|from|try|except|finally|with|as|in|not|and|or|is|yield|break|continue|pass|raise|lambda|assert|del|global|nonlocal)$",
                word,
            ):
                tokens.append({"type": "KEYWORD", "value": word})
            elif re.match(r"^[A-Z][A-Z0-9_]*$", word):
                tokens.append({"type": "VARIABLE", "value": word})
            elif re.match(r"^[a-z_]\w*$", word):
                tokens.append({"type": "VARIABLE", "value": word})
            elif re.match(r"^[0-9]+$", word):
                tokens.append({"type": "LITERAL", "value": word})
            else:
                tokens.append({"type": "OPERATOR", "value": word})
        return tokens

    def _normalize_tokens(self, tokens: List[Dict]) -> List[Dict]:
        """
        Normalize tokens for better comparison.

        Args:
            tokens: List of token dictionaries

        Returns:
            Normalized tokens
        """
        normalized = []

        for token in tokens:
            token_type = token.get("type", "UNKNOWN")
            value = token.get("value", "")

            # Skip whitespace and comments for fingerprinting
            if token_type in ["WHITESPACE", "COMMENT"]:
                continue

            # Normalize variable names (replace with placeholder)
            if token_type == "VARIABLE":
                # Keep first letter and type hint for better matching
                normalized_value = self._normalize_variable(value)
            elif token_type == "LITERAL":
                # Normalize string/number literals
                normalized_value = self._normalize_literal(value)
            else:
                normalized_value = value.strip()

            # Apply weight
            weight = self.token_weights.get(token_type, 1.0)

            normalized.append(
                {
                    "type": token_type,
                    "value": normalized_value,
                    "weight": weight,
                    "original": value,
                }
            )

        return normalized

    def _normalize_variable(self, var_name: str) -> str:
        """
        Normalize variable names for renaming resistance.

        Args:
            var_name: Original variable name

        Returns:
            Normalized variable name
        """
        if not var_name:
            return "VAR"

        # Keep common patterns
        if var_name in ["i", "j", "k"]:
            return "LOOP_VAR"
        elif len(var_name) == 1 and var_name.isalpha():
            return "VAR"
        elif var_name in ["self", "this"]:
            return "SELF"
        elif var_name.startswith("__") and var_name.endswith("__"):
            return "MAGIC_VAR"
        elif var_name.isupper():
            return "CONST"
        elif var_name.startswith("_"):
            return "PRIVATE_VAR"
        else:
            # Generic variable
            return "VAR"

    def _normalize_literal(self, literal: str) -> str:
        """
        Normalize literals for better matching.

        Args:
            literal: Original literal value

        Returns:
            Normalized literal
        """
        if not literal:
            return "LITERAL"

        # Numbers
        if literal.isdigit() or (literal.startswith("-") and literal[1:].isdigit()):
            return "NUM"
        # Booleans
        elif literal.lower() in ["true", "false"]:
            return "BOOL"
        # None/null
        elif literal.lower() in ["none", "null", "nil", "undefined"]:
            return "NULL"
        # Strings
        elif (literal.startswith('"') and literal.endswith('"')) or (
            literal.startswith("'") and literal.endswith("'")
        ):
            return "STR"
        else:
            return "LITERAL"

    def _get_adaptive_k(self, tokens: List[Dict[str, Any]]) -> int:
        """
        Get adaptive k-gram size based on code length and complexity.

        Args:
            tokens: List of tokens

        Returns:
            Optimal k-gram size
        """
        if not self.adaptive:
            return self.k or 5

        num_tokens = len(tokens)

        # Adaptive sizing based on code length
        if num_tokens < 50:
            return 3  # Small code, small k-grams
        elif num_tokens < 200:
            return 5  # Medium code
        elif num_tokens < 500:
            return 9  # Large code
        else:
            return 15  # Very large code

    def _get_adaptive_t(self, k: int) -> int:
        """
        Get adaptive window size based on k-gram size.

        Args:
            k: K-gram size

        Returns:
            Optimal window size
        """
        # Window size should be larger than k-gram size
        # Rule of thumb: t = k * 2
        return max(k * 2, 4)

    def _multi_pass_compare(
        self, tokens_a: List[Dict[str, Any]], tokens_b: List[Dict[str, Any]]
    ) -> float:
        """
        Perform multi-pass comparison with multiple k-gram sizes.

        Args:
            tokens_a: First normalized tokens
            tokens_b: Second normalized tokens

        Returns:
            Combined similarity score
        """
        similarities = []
        weights = []

        for k in self.k_sizes:
            t = self._get_adaptive_t(k)

            # Generate fingerprints with this k-gram size
            fp_a = self._get_winnowing_fingerprint(tokens_a, k, t)
            fp_b = self._get_winnowing_fingerprint(tokens_b, k, t)

            # Calculate similarity
            sim = self._jaccard_similarity(fp_a, fp_b)

            # Weight smaller k-grams higher (more sensitive to changes)
            weight = 1.0 / (k**0.5)

            similarities.append(sim)
            weights.append(weight)

        # Weighted average
        if sum(weights) == 0:
            return 0.0

        weighted_sum = sum(s * w for s, w in zip(similarities, weights))
        total_weight = sum(weights)

        return weighted_sum / total_weight

    def _single_pass_compare(
        self, tokens_a: List[Dict[str, Any]], tokens_b: List[Dict[str, Any]]
    ) -> float:
        """
        Perform single-pass comparison.

        Args:
            tokens_a: First normalized tokens
            tokens_b: Second normalized tokens

        Returns:
            Similarity score
        """
        k = self.k or self._get_adaptive_k(tokens_a)
        t = self.t or self._get_adaptive_t(k)

        fp_a = self._get_winnowing_fingerprint(tokens_a, k, t)
        fp_b = self._get_winnowing_fingerprint(tokens_b, k, t)

        return self._jaccard_similarity(fp_a, fp_b)

    def _get_winnowing_fingerprint(
        self, tokens: List[Dict[str, Any]], k: int, t: int
    ) -> List[str]:
        """
        Generate a winnowing fingerprint from tokens.

        Args:
            tokens: List of normalized tokens
            k: K-gram size
            t: Window size

        Returns:
            List of fingerprint hashes
        """
        if len(tokens) < k:
            if tokens:
                return [self._hash_tokens(tokens)]
            return []

        # Generate k-grams with weights
        k_grams = []
        for i in range(len(tokens) - k + 1):
            k_gram = tokens[i : i + k]
            k_grams.append(k_gram)

        # Hash k-grams (weighted if enabled)
        hashes = []
        for k_gram in k_grams:
            if self.weighted:
                hash_val = self._weighted_hash_tokens(k_gram)
            else:
                hash_val = self._hash_tokens(k_gram)
            hashes.append(hash_val)

        # Apply winnowing algorithm
        fingerprints = self._winnow(hashes, t)

        return fingerprints

    def _hash_tokens(self, tokens: List[Dict[str, Any]]) -> str:
        """
        Hash a list of tokens.

        Args:
            tokens: List of token dictionaries

        Returns:
            Hexadecimal hash string
        """
        # Concatenate token values
        text = " ".join(t["value"] for t in tokens)
        return hashlib.sha256(text.encode("utf-8")).hexdigest()

    def _weighted_hash_tokens(self, tokens: List[Dict[str, Any]]) -> str:
        """
        Hash tokens with weights applied.

        Args:
            tokens: List of token dictionaries with weights

        Returns:
            Weighted hexadecimal hash string
        """
        # Build weighted string
        parts = []
        for token in tokens:
            weight = token.get("weight", 1.0)
            value = token["value"]

            # Repeat high-weight tokens for emphasis
            repeat = max(1, int(weight))
            parts.extend([value] * repeat)

        text = " ".join(parts)
        return hashlib.sha256(text.encode("utf-8")).hexdigest()

    def _winnow(self, hashes: List[str], t: int) -> List[str]:
        """
        Apply the winnowing algorithm to select fingerprints.

        Args:
            hashes: List of hash values
            t: Window size

        Returns:
            Selected fingerprints
        """
        if len(hashes) < t:
            return hashes

        fingerprints = []
        last_min_pos = -1

        for i in range(len(hashes) - t + 1):
            window = hashes[i : i + t]
            min_hash = min(window)
            min_pos = i + window.index(min_hash)

            # Only add if min hash position is new
            if min_pos != last_min_pos:
                fingerprints.append(min_hash)
                last_min_pos = min_pos

        return fingerprints

    def _jaccard_similarity(self, set_a: List[str], set_b: List[str]) -> float:
        """
        Calculate Jaccard similarity between two lists.

        Args:
            set_a: First list
            set_b: Second list

        Returns:
            Jaccard similarity coefficient
        """
        if not set_a and not set_b:
            return 1.0
        if not set_a or not set_b:
            return 0.0

        set_a_set = set(set_a)
        set_b_set = set(set_b)

        intersection = len(set_a_set.intersection(set_b_set))
        union = len(set_a_set.union(set_b_set))

        if union == 0:
            return 0.0

        return intersection / union

    def _control_flow_similarity(self, parsed_a: Dict, parsed_b: Dict) -> float:
        """
        Calculate control flow similarity between two code samples.

        Args:
            parsed_a: First parsed code
            parsed_b: Second parsed code

        Returns:
            Control flow similarity score
        """
        # Extract control flow patterns
        cf_a = self._extract_control_flow(parsed_a)
        cf_b = self._extract_control_flow(parsed_b)

        if not cf_a and not cf_b:
            return 1.0
        if not cf_a or not cf_b:
            return 0.0

        # Calculate similarity
        return self._jaccard_similarity(cf_a, cf_b)

    def _extract_control_flow(self, parsed: Dict) -> List[str]:
        """
        Extract control flow patterns from parsed code.

        Args:
            parsed: Parsed code representation

        Returns:
            List of control flow patterns
        """
        patterns = []
        tokens = parsed.get("tokens", [])

        for i, token in enumerate(tokens):
            token_type = token.get("type", "")
            value = token.get("value", "")

            # Detect control flow keywords
            if token_type == "KEYWORD":
                if value in ["if", "elif", "else"]:
                    patterns.append("CONDITIONAL")
                elif value in ["for", "while"]:
                    patterns.append("LOOP")
                elif value == "return":
                    patterns.append("RETURN")
                elif value in ["try", "except", "finally"]:
                    patterns.append("EXCEPTION")
                elif value in ["break", "continue"]:
                    patterns.append("LOOP_CONTROL")

            # Detect function definitions
            elif token_type == "FUNCTION":
                patterns.append("FUNCTION_DEF")

            # Detect class definitions
            elif token_type == "CLASS":
                patterns.append("CLASS_DEF")

        return patterns

    def _detect_ai_generated(self, parsed: Dict) -> float:
        """
        Detect if code is likely AI-generated.

        Args:
            parsed: Parsed code representation

        Returns:
            AI detection score (0.0 = human, 1.0 = AI-generated)
        """
        if not self.ai_detection:
            return 0.0

        tokens = parsed.get("tokens", [])
        raw_code = parsed.get("raw", "")

        score = 0.0
        checks = 0

        # Check 1: Perplexity (variance in token types)
        token_types = [t.get("type", "") for t in tokens]
        type_counts = defaultdict(int)
        for t in token_types:
            type_counts[t] += 1

        if type_counts:
            # AI code tends to have more uniform distribution
            entropy = self._calculate_entropy(list(type_counts.values()))
            # Lower entropy = more likely AI
            if entropy < 2.0:
                score += 0.3
            checks += 1

        # Check 2: Burstiness (variance in sentence/token length)
        if tokens:
            lengths = [len(t.get("value", "")) for t in tokens]
            if lengths:
                mean_len = sum(lengths) / len(lengths)
                variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
                # Lower variance = more likely AI
                if variance < 10:
                    score += 0.2
                checks += 1

        # Check 3: Pattern repetition
        if tokens:
            patterns = [t.get("value", "") for t in tokens[:50]]
            unique_patterns = len(set(patterns))
            repetition_ratio = 1 - (unique_patterns / len(patterns))
            # Higher repetition = more likely AI
            if repetition_ratio > 0.3:
                score += 0.2
            checks += 1

        # Check 4: Comment style
        comment_tokens = [t for t in tokens if t.get("type") == "COMMENT"]
        if comment_tokens:
            # AI tends to add more comments
            comment_ratio = len(comment_tokens) / len(tokens)
            if comment_ratio > 0.1:
                score += 0.15
            checks += 1

        # Check 5: AI patterns in raw code
        for pattern in self.ai_patterns:
            if re.search(pattern, raw_code, re.IGNORECASE):
                score += 0.15
                checks += 1
                break

        # Normalize score
        if checks > 0:
            return min(1.0, score)

        return 0.0

    def _calculate_entropy(self, values: List[int]) -> float:
        """
        Calculate Shannon entropy of a distribution.

        Args:
            values: List of counts

        Returns:
            Entropy value
        """
        total = sum(values)
        if total == 0:
            return 0.0

        entropy = 0.0
        for count in values:
            if count > 0:
                p = count / total
                entropy -= p * math.log2(p)

        return entropy
