"""Loader for the measured human-code false-positive baseline.

Single source of truth for FP numbers surfaced in the product (accuracy page,
AI-detector results banner, dossier evidence caveats). The artifact is
regenerated by ``scripts/measure_human_fp.py``; see
``docs/HUMAN_FP_BASELINE.md`` for methodology and honest caveats.

The numbers describe the detector AS IT WAS WHEN MEASURED. Changing a signal's
definition, the classifier, or the thresholds makes them stale until the
measurement is re-run; ``measured_at`` is exposed so callers can show the date.
"""

from __future__ import annotations

import copy
import json
import logging
import math
from functools import lru_cache
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_BASELINE_PATH = Path(__file__).resolve().parent / "human_fp_baseline.json"

#: severity band -> (baseline key, corpus the key was measured on)
_BAND_KEYS: dict[str, str] = {"high": "fp_at_0.70", "medium": "fp_at_0.40"}
_PRIMARY_CORPUS = "kaggle_student_code"


@lru_cache(maxsize=1)
def _load() -> dict[str, Any]:
    try:
        payload = json.loads(_BASELINE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.info("Human FP baseline unavailable: %s", exc)
        return {}
    if not isinstance(payload, dict):
        logger.warning("Human FP baseline is not a JSON object; ignoring it")
        return {}
    return payload


def load_human_fp_baseline() -> dict[str, Any]:
    """Return a COPY of the tracked baseline payload, or an empty dict when absent.

    The cached dict used to be returned directly, so a caller that modified the
    result changed the baseline for everyone in the process.
    """
    return copy.deepcopy(_load())


def reload_human_fp_baseline() -> None:
    """Drop the cached payload so the next call re-reads the file."""
    _load.cache_clear()


def band_caveat(severity: str) -> str:
    """Band-relative FP caveat for AI evidence, empty for low/unknown bands.

    Args:
        severity: The evidence severity band ("high" | "medium" | "low").
            Matching is case-insensitive.

    Returns:
        Human-readable caveat stating the measured share of real student
        submissions that score in this band, or "" when the band carries no
        measured FP concern.
    """
    caveats = _load().get("band_caveats")
    if not isinstance(caveats, dict):
        return ""
    return str(caveats.get(str(severity).strip().lower(), ""))


def wilson_interval(successes: int, total: int, z: float = 1.96) -> tuple[float, float]:
    """Wilson score interval for a binomial proportion (default 95%)."""
    if total <= 0:
        return 0.0, 1.0
    p = successes / total
    denominator = 1.0 + z * z / total
    centre = (p + z * z / (2 * total)) / denominator
    margin = z * math.sqrt(p * (1 - p) / total + z * z / (4 * total * total)) / denominator
    return max(0.0, centre - margin), min(1.0, centre + margin)


def fp_rate_with_interval(severity: str) -> dict[str, Any] | None:
    """Measured FP rate for a band with its 95% interval, or None if unavailable.

    ``fp_at_*`` values in the baseline are point estimates; with 174 files and 4
    flagged, the plausible range is roughly 1%-6%, not "about 2%". The interval is
    derived from the stored corpus size and rate.
    """
    key = _BAND_KEYS.get(str(severity).strip().lower())
    corpus = (_load().get("corpora") or {}).get(_PRIMARY_CORPUS)
    if key is None or not isinstance(corpus, dict):
        return None
    count, rate = corpus.get("count"), corpus.get(key)
    if not isinstance(count, int) or count <= 0 or not isinstance(rate, (int, float)):
        return None
    flagged = round(rate * count)
    low, high = wilson_interval(flagged, count)
    return {
        "rate": rate,
        "flagged": flagged,
        "count": count,
        "ci95": (round(low, 4), round(high, 4)),
        "corpus": _PRIMARY_CORPUS,
    }


def band_caveat_with_interval(severity: str) -> str:
    """The stored caveat plus the 95% interval and sample size, when known."""
    caveat = band_caveat(severity)
    stats = fp_rate_with_interval(severity)
    if not caveat or stats is None:
        return caveat
    low, high = stats["ci95"]
    return (
        f"{caveat} (95% interval {low:.1%}-{high:.1%}; "
        f"{stats['flagged']} of {stats['count']} files in one Python corpus)"
    )


def baseline_measured_at() -> str:
    """Date the baseline was measured (ISO string), or "" if unknown."""
    return str(_load().get("measured_at", ""))
