"""Loader for the measured human-code false-positive baseline.

Single source of truth for FP numbers surfaced in the product (accuracy page,
AI-detector results banner, dossier evidence caveats). The artifact is
regenerated by ``scripts/measure_human_fp.py``; see
``docs/HUMAN_FP_BASELINE.md`` for methodology and honest caveats.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict

logger = logging.getLogger(__name__)

_BASELINE_PATH = Path(__file__).resolve().parent / "human_fp_baseline.json"


@lru_cache(maxsize=1)
def load_human_fp_baseline() -> Dict[str, Any]:
    """Return the tracked baseline payload, or an empty dict when absent."""
    try:
        return json.loads(_BASELINE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.info("Human FP baseline unavailable: %s", exc)
        return {}


def band_caveat(severity: str) -> str:
    """Band-relative FP caveat for AI evidence, empty for low/unknown bands.

    Args:
        severity: The evidence severity band ("high" | "medium" | "low").

    Returns:
        Human-readable caveat stating the measured share of real student
        submissions that score in this band, or "" when the band carries no
        measured FP concern.
    """
    return str(load_human_fp_baseline().get("band_caveats", {}).get(severity, ""))
