"""
AI-Generated Code Detection Module for CodeProvenance.

Detects code likely generated by Large Language Models (LLMs) like ChatGPT, Copilot, etc.
Addresses the growing concern of AI-generated submissions in academic settings.
"""

import re
import hashlib
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass
from collections import Counter
import numpy as np


@dataclass
class AIDetectionResult:
    """Result of AI detection analysis."""
    is_likely_ai: bool
    ai_score: float  # 0.0 - 1.0 (higher = more likely AI)
    confidence: float  # Confidence in the prediction
    indicators: Dict[str, float]  # Individual indicator scores
    explanation: str


class AIDetector:
    """
    Detects code likely generated by LLMs.
    
    Uses multiple heuristics and statistical analysis to identify AI-generated code.
    """
    
    # Common AI generation patterns
    AI_PATTERNS = {
        # Comment patterns
        'excessive_comments': r'//\s*(?:This|This code|This function|Note|Step)',
        'tutorial_style_comments': r'//\s*(?:Here we|First,|Next,|Finally,|Let\'s)',
        'markdown_headers': r'^#+\s+\w+',  # Markdown headers in code
        
        # Code style patterns
        'verbose_varnames': r'\b(the_|a_|an_)',  # Verbose variable names
        'generic_function_names': r'\b(process|handle|execute|perform)[\w]+\(',
        'overly_descriptive': r'\b(temp_variable|helper_function|utility_)\w*',
        
        # Structure patterns
        'perfect_formatting': r'^\s{4}',  # Exactly 4 spaces (ChatGPT default)
        'consistent_newlines': r'\n\n\n',  # Double blank lines
        
        # Content patterns
        'safety_patterns': r'(?:try-catch|error handling|edge cases|boundary conditions)',
        'boilerplate_intro': r'^(?:Here\'s|Certainly|Below is|Sure,|Of course)',
    }
    
    # Known AI-specific code signatures
    AI_SIGNATURES = {
        'chatgpt_comment': r'(?i)(?:as an ai|i don\'t have|please note that|i cannot)',
        'copilot_import': r'from github_copilot',
        'template_boilerplate': r'"""[\w\s]+"""',
    }
    
    def __init__(self, threshold: float = 0.6):
        """
        Initialize AI detector.
        
        Args:
            threshold: Score threshold for flagging as AI-generated (0.0-1.0)
        """
        self.threshold = threshold
    
    def analyze(self, code: str, language: str = 'unknown') -> AIDetectionResult:
        """
        Analyze code for AI generation indicators.
        
        Args:
            code: Source code to analyze
            language: Programming language
            
        Returns:
            AIDetectionResult with analysis
        """
        indicators = {}
        
        # Pattern-based detection
        indicators['ai_patterns'] = self._check_ai_patterns(code)
        indicators['comment_density'] = self._analyze_comment_density(code, language)
        indicators['formatting_consistency'] = self._check_formatting_consistency(code)
        indicators['variable_naming'] = self._analyze_variable_naming(code)
        indicators['code_entropy'] = self._calculate_entropy(code)
        indicators['repetition'] = self._detect_repetition(code)
        indicators['boilerplate'] = self._detect_boilerplate(code)
        indicators['structural_uniformity'] = self._analyze_structural_uniformity(code)
        
        # Calculate overall AI score
        ai_score = self._calculate_ai_score(indicators)
        
        # Determine if likely AI-generated
        is_likely_ai = ai_score >= self.threshold
        
        # Calculate confidence
        confidence = self._calculate_confidence(indicators)
        
        # Generate explanation
        explanation = self._generate_explanation(indicators, ai_score)
        
        return AIDetectionResult(
            is_likely_ai=is_likely_ai,
            ai_score=ai_score,
            confidence=confidence,
            indicators=indicators,
            explanation=explanation
        )
    
    def _check_ai_patterns(self, code: str) -> float:
        """Check for known AI generation patterns."""
        matches = 0
        total_checks = len(self.AI_PATTERNS) + len(self.AI_SIGNATURES)
        
        for pattern in self.AI_PATTERNS.values():
            if re.search(pattern, code, re.MULTILINE | re.IGNORECASE):
                matches += 1
        
        for pattern in self.AI_SIGNATURES.values():
            if re.search(pattern, code):
                matches += 1
        
        return matches / max(total_checks, 1)
    
    def _analyze_comment_density(self, code: str, language: str) -> float:
        """Analyze comment density (AI often over-comments)."""
        if not code.strip():
            return 0.0
        
        # Count lines
        lines = code.split('\n')
        total_lines = len([l for l in lines if l.strip()])
        
        if total_lines == 0:
            return 0.0
        
        # Count comments based on language
        comment_lines = 0
        
        if language in ('python',):
            # Python comments
            comment_lines = len([l for l in lines if l.strip().startswith('#')])
            # Docstrings
            comment_lines += len(re.findall(r'""".*?"""', code, re.DOTALL))
        elif language in ('javascript', 'java', 'c', 'cpp', 'typescript', 'c#'):
            # Single-line comments
            comment_lines = len([l for l in lines if '//' in l])
            # Multi-line comments
            comment_lines += len(re.findall(r'/\*.*?\*/', code, re.DOTALL))
        
        density = comment_lines / total_lines
        
        # Higher density is more suspicious
        # Normal range is 0.1-0.2, AI tends to be >0.3
        if density > 0.5:
            return 1.0
        elif density > 0.3:
            return 0.7
        elif density > 0.2:
            return 0.4
        else:
            return 0.1
    
    def _check_formatting_consistency(self, code: str) -> float:
        """Check for overly consistent formatting (AI signature)."""
        lines = [l for l in code.split('\n') if l.strip()]
        
        if len(lines) < 5:
            return 0.0
        
        # Check indentation consistency
        indents = []
        for line in lines:
            match = re.match(r'^(\s*)', line)
            if match:
                indents.append(len(match.group(1)))
        
        if not indents:
            return 0.0
        
        # AI often uses exactly 4 spaces
        indent_counts = Counter(indents)
        most_common_indent = indent_counts.most_common(1)[0]
        
        # If >80% of lines use the same indent, suspicious
        if most_common_indent[1] / len(indents) > 0.8:
            return 0.7
        
        # Check for perfect blank line consistency
        blank_lines = 0
        for i, line in enumerate(code.split('\n')):
            if not line.strip():
                blank_lines += 1
        
        blank_ratio = blank_lines / max(len(lines), 1)
        
        # Perfect blank line ratio is suspicious
        if 0.15 < blank_ratio < 0.25:
            return 0.5
        
        return 0.2
    
    def _analyze_variable_naming(self, code: str) -> float:
        """Analyze variable naming patterns."""
        # Find variable declarations
        variables = re.findall(r'\b([a-z][a-zA-Z0-9_]*)\s*=', code)
        
        if len(variables) < 3:
            return 0.0
        
        # Count suspicious naming patterns
        suspicious = 0
        
        # Very long names
        long_names = [v for v in variables if len(v) > 15]
        suspicious += len(long_names)
        
        # Names with underscores (snake_case) - more common in AI
        underscore_names = [v for v in variables if '_' in v]
        suspicious += len(underscore_names) * 0.3
        
        # Generic names
        generic_patterns = [
            r'^(temp|tmp)_\w+',
            r'^helper_\w+',
            r'^data_\w+',
            r'^result_\w+',
            r'^item_\w+',
        ]
        for pattern in generic_patterns:
            matches = [v for v in variables if re.match(pattern, v)]
            suspicious += len(matches) * 0.5
        
        score = suspicious / len(variables)
        return min(score, 1.0)
    
    def _calculate_entropy(self, code: str) -> float:
        """Calculate code entropy (lower = more repetitive = more likely AI)."""
        # Remove whitespace for character analysis
        chars = [c for c in code if c.isalnum()]
        
        if len(chars) < 10:
            return 0.5
        
        # Calculate character frequency entropy
        freq = Counter(chars)
        total = len(chars)
        
        entropy = 0.0
        for count in freq.values():
            p = count / total
            if p > 0:
                entropy -= p * np.log2(p)
        
        # Normalize entropy (max entropy for alphanumeric is ~4.17)
        normalized_entropy = entropy / 4.17
        
        # Very low entropy (<0.5) is suspicious
        if normalized_entropy < 0.4:
            return 0.8
        elif normalized_entropy < 0.5:
            return 0.5
        elif normalized_entropy < 0.6:
            return 0.3
        else:
            return 0.1
    
    def _detect_repetition(self, code: str) -> float:
        """Detect repetitive patterns (common in AI-generated code)."""
        # Tokenize into n-grams
        lines = [l.strip() for l in code.split('\n') if l.strip()]
        
        if len(lines) < 10:
            return 0.0
        
        # Find repeated lines
        line_counts = Counter(lines)
        repeats = sum(1 for count in line_counts.values() if count > 1)
        
        # Calculate repetition ratio
        repeat_ratio = repeats / len(set(lines))
        
        if repeat_ratio > 0.3:
            return 0.8
        elif repeat_ratio > 0.2:
            return 0.5
        elif repeat_ratio > 0.1:
            return 0.3
        else:
            return 0.1
    
    def _detect_boilerplate(self, code: str) -> float:
        """Detect common AI boilerplate patterns."""
        boilerplate_score = 0.0
        
        # Check for common boilerplate
        boilerplate_patterns = [
            (r'def\s+\w+\s*\([^)]*\):\s*"""', 0.3),  # Generic docstring
            (r'print\s*\(\s*["\']', 0.1),  # Print statements
            (r'if\s+__name__\s*==\s*["\']__main__["\']', 0.1),  # Main guard
            (r'#.*(?:import|include)\s+\w+', 0.1),  # Imports
            (r'try:\s+.*except', 0.2),  # Try-except
            (r'class\s+\w+:', 0.1),  # Class definition
        ]
        
        for pattern, weight in boilerplate_patterns:
            if re.search(pattern, code):
                boilerplate_score += weight
        
        return min(boilerplate_score, 1.0)
    
    def _analyze_structural_uniformity(self, code: str) -> float:
        """Analyze structural uniformity of code."""
        lines = code.split('\n')
        code_lines = [l for l in lines if l.strip() and not l.strip().startswith('#')]
        
        if len(code_lines) < 5:
            return 0.0
        
        # Calculate line length variance
        lengths = [len(l) for l in code_lines]
        if lengths:
            variance = np.var(lengths) if len(lengths) > 1 else 0
            std_dev = np.sqrt(variance)
            mean_length = np.mean(lengths)
            
            # Very low variance (all lines similar length) is suspicious
            if mean_length > 0:
                cv = std_dev / mean_length  # Coefficient of variation
                
                if cv < 0.3:
                    return 0.6
                elif cv < 0.5:
                    return 0.3
        
        return 0.1
    
    def _calculate_ai_score(self, indicators: Dict[str, float]) -> float:
        """Calculate overall AI generation score."""
        weights = {
            'ai_patterns': 0.25,
            'comment_density': 0.15,
            'formatting_consistency': 0.10,
            'variable_naming': 0.10,
            'code_entropy': 0.15,
            'repetition': 0.10,
            'boilerplate': 0.10,
            'structural_uniformity': 0.05,
        }
        
        total_score = 0.0
        total_weight = 0.0
        
        for key, weight in weights.items():
            if key in indicators:
                total_score += indicators[key] * weight
                total_weight += weight
        
        if total_weight > 0:
            return total_score / total_weight
        
        return 0.0
    
    def _calculate_confidence(self, indicators: Dict[str, float]) -> float:
        """Calculate confidence in the prediction."""
        # Higher confidence when indicators agree
        values = list(indicators.values())
        
        if not values:
            return 0.0
        
        # Calculate agreement (lower variance = higher confidence)
        variance = np.var(values)
        
        # Map variance to confidence (0-1)
        # High variance = low confidence, low variance = high confidence
        confidence = 1.0 - min(variance * 2, 1.0)
        
        return confidence
    
    def _generate_explanation(self, indicators: Dict[str, float], score: float) -> str:
        """Generate human-readable explanation."""
        if score >= 0.7:
            threshold = "HIGH"
        elif score >= 0.5:
            threshold = "MODERATE"
        else:
            threshold = "LOW"
        
        explanations = []
        
        if indicators.get('ai_patterns', 0) > 0.3:
            explanations.append("Detected common AI generation patterns")
        
        if indicators.get('comment_density', 0) > 0.5:
            explanations.append("Unusually high comment density")
        
        if indicators.get('code_entropy', 0) > 0.5:
            explanations.append("Low code entropy suggests repetitive/AI-like patterns")
        
        if indicators.get('repetition', 0) > 0.5:
            explanations.append("Significant code repetition detected")
        
        if indicators.get('formatting_consistency', 0) > 0.5:
            explanations.append("Overly consistent formatting")
        
        if not explanations:
            explanations.append("No strong indicators of AI generation")
        
        return f"[{threshold} RISK] {'; '.join(explanations)}"


class StatisticalAIDetector:
    """
    Statistical analysis-based AI detector.
    
    Uses statistical properties of code to detect AI generation.
    """
    
    def __init__(self):
        self.known_ai_hashes = set()  # Known AI code hashes
    
    def analyze_statistical_properties(self, code: str) -> Dict[str, float]:
        """
        Analyze statistical properties of code.
        
        Args:
            code: Source code
            
        Returns:
            Dictionary of statistical metrics
        """
        # Tokenize
        tokens = re.findall(r'\b\w+\b', code)
        
        # Calculate metrics
        metrics = {
            'token_count': len(tokens),
            'unique_token_ratio': len(set(tokens)) / max(len(tokens), 1),
            'avg_token_length': np.mean([len(t) for t in tokens]) if tokens else 0,
            'max_token_length': max([len(t) for t in tokens]) if tokens else 0,
            'line_count': len(code.split('\n')),
            'char_count': len(code),
            'whitespace_ratio': code.count(' ') / max(len(code), 1),
            'newline_ratio': code.count('\n') / max(len(code), 1),
        }
        
        # Calculate n-gram diversity
        bigrams = [code[i:i+2] for i in range(len(code)-1)]
        trigrams = [code[i:i+3] for i in range(len(code)-2)]
        
        metrics['bigram_diversity'] = len(set(bigrams)) / max(len(bigrams), 1)
        metrics['trigram_diversity'] = len(set(trigrams)) / max(len(trigrams), 1)
        
        return metrics
    
    def compare_to_known_patterns(self, code: str) -> float:
        """
        Compare code to known AI-generated patterns.
        
        Args:
            code: Source code
            
        Returns:
            Similarity score to known AI patterns (0-1)
        """
        # This would use a trained classifier in production
        # For now, use simple heuristics
        
        code_hash = hashlib.md5(code.encode()).hexdigest()
        
        if code_hash in self.known_ai_hashes:
            return 1.0
        
        # Check for known AI markers
        markers = [
            (r'generated by', 0.5),
            (r'created by', 0.5),
            (r'AI assistant', 0.8),
            (r'language model', 0.8),
        ]
        
        score = 0.0
        for pattern, weight in markers:
            if re.search(pattern, code, re.IGNORECASE):
                score += weight
        
        return min(score, 1.0)


class EnsembleAIDetector:
    """
    Ensemble AI detector combining multiple detection methods.
    """
    
    def __init__(self, threshold: float = 0.6):
        """
        Initialize ensemble detector.
        
        Args:
            threshold: Score threshold for flagging
        """
        self.pattern_detector = AIDetector(threshold)
        self.statistical_detector = StatisticalAIDetector()
        self.threshold = threshold
    
    def analyze(self, code: str, language: str = 'unknown') -> AIDetectionResult:
        """
        Analyze code using ensemble of methods.
        
        Args:
            code: Source code
            language: Programming language
            
        Returns:
            Combined AIDetectionResult
        """
        # Pattern-based analysis
        pattern_result = self.pattern_detector.analyze(code, language)
        
        # Statistical analysis
        stats = self.statistical_detector.analyze_statistical_properties(code)
        known_match = self.statistical_detector.compare_to_known_patterns(code)
        
        # Combine scores
        combined_score = (
            pattern_result.ai_score * 0.7 +
            known_match * 0.3
        )
        
        # Adjust confidence based on statistical agreement
        new_confidence = (pattern_result.confidence + 1.0 - stats['unique_token_ratio']) / 2
        
        # Merge indicators
        all_indicators = pattern_result.indicators.copy()
        all_indicators.update({
            'known_ai_match': known_match,
            'unique_token_ratio': stats['unique_token_ratio'],
            'bigram_diversity': stats.get('bigram_diversity', 0),
            'trigram_diversity': stats.get('trigram_diversity', 0),
        })
        
        is_likely_ai = combined_score >= self.threshold
        
        return AIDetectionResult(
            is_likely_ai=is_likely_ai,
            ai_score=combined_score,
            confidence=new_confidence,
            indicators=all_indicators,
            explanation=pattern_result.explanation
        )


# Convenience function
def detect_ai_code(
    code: str,
    language: str = 'unknown',
    threshold: float = 0.6,
    use_ensemble: bool = True
) -> AIDetectionResult:
    """
    Detect if code was likely generated by an LLM.
    
    Args:
        code: Source code to analyze
        language: Programming language
        threshold: AI score threshold
        use_ensemble: Use ensemble detector (more accurate)
        
    Returns:
        AIDetectionResult
    """
    if use_ensemble:
        detector = EnsembleAIDetector(threshold)
    else:
        detector = AIDetector(threshold)
    
    return detector.analyze(code, language)
