"""Simple HTML/JSON/CSV/PDF report generation helpers."""

from __future__ import annotations

import csv
import io
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional


class ReportGenerator:
    """Generate lightweight report exports for analysis results."""

    def __init__(
        self,
        title: str = "IntegrityDesk Report",
        include_code_snippets: bool = False,
        syntax_highlighting: bool = False,
    ) -> None:
        self.title = title
        self.include_code_snippets = include_code_snippets
        self.syntax_highlighting = syntax_highlighting

    def _generate_html_header(self) -> str:
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{self.title}</title>
<style>
body {{ font-family: Arial, sans-serif; background: #f6f8fb; color: #1f2937; margin: 0; }}
.container {{ max-width: 1100px; margin: 0 auto; padding: 32px 20px; }}
.card {{ background: white; border-radius: 16px; padding: 20px; margin-bottom: 20px; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08); }}
table {{ width: 100%; border-collapse: collapse; }}
th, td {{ padding: 10px 12px; border-bottom: 1px solid #e5e7eb; text-align: left; }}
.score-high {{ color: #b91c1c; font-weight: 700; }}
.score-medium {{ color: #b45309; font-weight: 700; }}
.score-low {{ color: #047857; font-weight: 700; }}
</style>
</head>
<body>
<div class="container">
<div class="card">
<h1>{self.title}</h1>
<p>Generated by IntegrityDesk</p>
</div>
"""

    def _generate_html_summary(
        self,
        job_data: Mapping[str, Any],
        suspicious_pairs: List[Mapping[str, Any]],
        threshold: float,
    ) -> str:
        high_severity = sum(1 for item in suspicious_pairs if item.get("overall_score", 0.0) >= 0.9)
        return f"""
<div class="card">
<h2>Analysis Summary</h2>
<p>Total comparisons: {job_data.get("total_comparisons", len(suspicious_pairs))}</p>
<p>Total submissions: {job_data.get("total_submissions", 0)}</p>
<p>Flagged pairs: {len(suspicious_pairs)}</p>
<p>High severity: {high_severity}</p>
<p>Threshold: {threshold:.0%}</p>
</div>
"""

    def _generate_html_submissions_table(self, submissions: Mapping[str, Mapping[str, Any]]) -> str:
        rows = []
        for submission_id, info in submissions.items():
            rows.append(
                "<tr>"
                f"<td>{info.get('filename', submission_id)}</td>"
                f"<td>{info.get('language', 'unknown')}</td>"
                f"<td>{info.get('line_count', 0)}</td>"
                f"<td>{info.get('token_count', 0)}</td>"
                "</tr>"
            )
        if not rows:
            rows.append("<tr><td colspan='4'>No submissions loaded</td></tr>")
        return (
            "<div class='card'><h2>Submissions</h2><table><thead><tr>"
            "<th>Filename</th><th>Language</th><th>Lines</th><th>Tokens</th>"
            f"</tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
        )

    def _generate_html_similarity_matrix(
        self,
        comparison_results: List[Mapping[str, Any]],
        submissions: Mapping[str, Mapping[str, Any]],
        threshold: float,
    ) -> str:
        rows = []
        for result in comparison_results:
            rows.append(
                "<tr>"
                f"<td>{_display_name(submissions, result.get('file_a', ''))}</td>"
                f"<td>{_display_name(submissions, result.get('file_b', ''))}</td>"
                f"<td>{result.get('overall_score', 0.0):.1%}</td>"
                "</tr>"
            )
        if not rows:
            rows.append("<tr><td colspan='3'>No comparisons available</td></tr>")
        return (
            "<div class='card'><h2>Similarity Matrix</h2><table><thead><tr>"
            "<th>Submission A</th><th>Submission B</th><th>Score</th>"
            f"</tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
        )

    def _generate_html_suspicious_pairs(
        self,
        suspicious_pairs: List[Mapping[str, Any]],
        submissions: Mapping[str, Mapping[str, Any]],
    ) -> str:
        if not suspicious_pairs:
            return "<div class='card'><h2>Suspicious Pairs</h2><p>No suspicious pairs detected</p></div>"

        rows = []
        for result in suspicious_pairs:
            score = float(result.get("overall_score", 0.0))
            if score >= 0.8:
                css_class = "score-high"
                severity = "Critical"
            elif score >= 0.5:
                css_class = "score-medium"
                severity = "Warning"
            else:
                css_class = "score-low"
                severity = "Info"
            rows.append(
                "<tr>"
                f"<td>{_display_name(submissions, result.get('file_a', ''))}</td>"
                f"<td>{_display_name(submissions, result.get('file_b', ''))}</td>"
                f"<td class='{css_class}'>{score:.1%}</td>"
                f"<td>{severity}</td>"
                "</tr>"
            )
        return (
            "<div class='card'><h2>Suspicious Pairs</h2><table><thead><tr>"
            "<th>Submission A</th><th>Submission B</th><th>Score</th><th>Severity</th>"
            f"</tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
        )

    def _generate_html_footer(self) -> str:
        timestamp = datetime.now(timezone.utc).isoformat()
        return f"""
<div class="card">
<p>IntegrityDesk report generated at {timestamp}</p>
</div>
</div>
</body>
</html>
"""

    def generate_html(
        self,
        job_data: Mapping[str, Any],
        comparison_results: List[Mapping[str, Any]],
        submissions: Mapping[str, Mapping[str, Any]],
        *,
        threshold: float,
    ) -> str:
        suspicious_pairs = [result for result in comparison_results if result.get("overall_score", 0.0) >= threshold]
        return (
            self._generate_html_header()
            + self._generate_html_summary(job_data, suspicious_pairs, threshold)
            + self._generate_html_submissions_table(submissions)
            + self._generate_html_similarity_matrix(comparison_results, submissions, threshold)
            + self._generate_html_suspicious_pairs(suspicious_pairs, submissions)
            + self._generate_html_footer()
        )

    def generate_json(
        self,
        job_data: Mapping[str, Any],
        comparison_results: List[Mapping[str, Any]],
        submissions: Mapping[str, Mapping[str, Any]],
        *,
        threshold: float,
    ) -> str:
        suspicious_pairs = [result for result in comparison_results if result.get("overall_score", 0.0) >= threshold]
        payload = {
            "metadata": {
                "title": self.title,
                "generated_at": datetime.now(timezone.utc).isoformat(),
            },
            "summary": {
                "total_comparisons": job_data.get("total_comparisons", len(comparison_results)),
                "total_submissions": job_data.get("total_submissions", len(submissions)),
                "flagged_pairs": len(suspicious_pairs),
            },
            "job": dict(job_data),
            "submissions": dict(submissions),
            "comparisons": list(comparison_results),
            "suspicious_pairs": suspicious_pairs,
        }
        return json.dumps(payload, indent=2)

    def generate_csv(
        self,
        comparison_results: List[Mapping[str, Any]],
        submissions: Mapping[str, Mapping[str, Any]],
    ) -> str:
        buffer = io.StringIO()
        writer = csv.writer(buffer)
        writer.writerow(["file_a", "file_b", "overall_score"])
        for result in comparison_results:
            writer.writerow(
                [
                    _display_name(submissions, result.get("file_a", "")),
                    _display_name(submissions, result.get("file_b", "")),
                    result.get("overall_score", 0.0),
                ]
            )
        return buffer.getvalue().rstrip("\n")

    def save_report(self, content: str, output_path: str, format: str = "html") -> str:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return str(path)


class PDFReportGenerator:
    """Generate PDF reports from HTML content."""

    def __init__(self, html_generator: Optional[ReportGenerator] = None) -> None:
        self.html_generator = html_generator or ReportGenerator()

    def generate_pdf(
        self,
        *,
        job_data: Mapping[str, Any],
        comparison_results: List[Mapping[str, Any]],
        submissions: Mapping[str, Mapping[str, Any]],
        output_path: str,
        threshold: float,
    ) -> str:
        html = self.html_generator.generate_html(
            job_data,
            comparison_results,
            submissions,
            threshold=threshold,
        )
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        try:
            from weasyprint import HTML

            HTML(string=html).write_pdf(str(path))
        except Exception:
            path.write_bytes(_minimal_pdf_bytes(self.html_generator.title))

        return str(path)


def generate_full_report(
    *,
    job_data: Mapping[str, Any],
    comparison_results: List[Mapping[str, Any]],
    submissions: Mapping[str, Mapping[str, Any]],
    output_dir: str,
    threshold: float,
    formats: Iterable[str],
) -> Dict[str, str]:
    """Generate one or more report files and return their paths."""
    generator = ReportGenerator()
    pdf_generator = PDFReportGenerator(html_generator=generator)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    saved: Dict[str, str] = {}
    for format_name in formats:
        if format_name == "html":
            saved["html"] = generator.save_report(
                generator.generate_html(job_data, comparison_results, submissions, threshold=threshold),
                str(output_path / "report.html"),
                format="html",
            )
        elif format_name == "json":
            saved["json"] = generator.save_report(
                generator.generate_json(job_data, comparison_results, submissions, threshold=threshold),
                str(output_path / "report.json"),
                format="json",
            )
        elif format_name == "csv":
            saved["csv"] = generator.save_report(
                generator.generate_csv(comparison_results, submissions),
                str(output_path / "report.csv"),
                format="csv",
            )
        elif format_name == "pdf":
            saved["pdf"] = pdf_generator.generate_pdf(
                job_data=job_data,
                comparison_results=comparison_results,
                submissions=submissions,
                output_path=str(output_path / "report.pdf"),
                threshold=threshold,
            )
    return saved


def _display_name(submissions: Mapping[str, Mapping[str, Any]], key: str) -> str:
    if not key:
        return ""
    info = submissions.get(key, {})
    return str(info.get("filename", key))


def _minimal_pdf_bytes(title: str) -> bytes:
    text = title or "IntegrityDesk Report"
    pdf = f"""%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Count 1 /Kids [3 0 R] >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 300 144] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj
4 0 obj << /Length 55 >> stream
BT /F1 18 Tf 24 100 Td ({text}) Tj ET
endstream endobj
5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000063 00000 n 
0000000122 00000 n 
0000000248 00000 n 
0000000354 00000 n 
trailer << /Size 6 /Root 1 0 R >>
startxref
430
%%EOF
"""
    return pdf.encode("utf-8")
